BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB

XXXXXXX gettext(u'електронну пошту підтверджено') XXXXXXXX

XXXXXXX
XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX
X

XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX
X

XXXXXXXXXXX XX X
    XXXXXXX X X XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X X
    XXXXXXX X X XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXX XXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXX
    XXXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXX
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXX
             gettext(u'перейти на сторінку входу') 
        XXXX
    XXXXXX
XXXXXX

BBBBBBBB