BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB

XXXXXXX gettext(u'підтвердження електронної пошти') XXXXXXXX


XXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXX
   XXXXXX XXXX
XXXXXXXXXXXXXXXXXXXXXXXXX XX

XXXXXXXXXXXX X
    XXXXXXXXXXX XXXXX
    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXX XXXXX

X

XXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXXXXX XXXXXX
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXX XXXX XXXXX
    XXXXXXXXXXX XXXXXXX

    XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
X

XX XXXXXX XX
XXXXXXXXXXXX X
    XXXXXX XXXXX
    XXXXXXX XXXXX
    XXXXXXX X XXXX XXXXX

    XXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX

    XXXXXXXXXXX XXXXXXXX XXX XXXX XXXXX
    XXXXXX XXXXXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXX
X

XXXXXXXXXXX XX X
    XXXXXXX X X XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XXXXXXXXXXX X X
    XXXXXXX X X XXXXX
    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XX XXXXX XX
XXXXXXXXXXXXX X
    XXXXXXXXXXXX XXXX
    XXXXXX XXXXXXXX
X

XX XXXXXX XX
XXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXX
    XXXXXXXX XXXX XXXXX

    XXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXX

    XXXXXX XXXXXXXX
    XXXXXXXXXXX XXXXXXXX

    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXX

    XXXXXXXXXXX XXX XXXX XXXXX
X

XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXXXXXXXXXXXX
X

XX XXXXXX XX
XXXXXX XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXX X
        XXXXXXXX XXXX XXXXX
    X

    XXXXXXXXXXX XX X
        XXXXXXXXXX XXXXX
    X

    XXXXXXXXXXX X X
        XXXXXXXXXX XXXXX
    X
X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXX gettext(u'Підтвердіть електронну пошту') XXXXX

        XXX
             gettext(u'Ми надіслали лист на адресу') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX

        XXX
             gettext(u'Перейдіть за посиланням у листі, щоб підтвердити пошту та опублікувати оголошення.') 
        XXXX

        XX XXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
             gettext(u'Перейти на головну') 
        XXXX

    XXXXXX
XXXXXX

BBBBBBBB