BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX gettext(u'вхід') XXXXXXXX
XXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'вхід') XXXXX
    XX XXXXXXXXXXXXXXXXX gettext(u'увійдіть, щоб керувати своїми оголошеннями') XXXX

    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'війти') XXXXXXXXX
    XXXXXXX

    BB BBBXX XXXXXXXXXXXXXXXXXXFFFFXXXXBBBBB

    BB BBBBBBBBBBB BBB BBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'надіслати посилання повторно') 
      XXXXXXXXX
    XXXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBXX gettext(u'реєстрація') XXXX
      XXXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'на головну') XXXX
    XXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB