
BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
XXXXXXX gettext(u'реєстрація') XXXXXXXX
XXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX gettext(u'реєстрація') XXXXX
      XX XXXXXXXXXXXXXXXXX gettext(u'створіть обліковий запис за хвилину') XXXX
      XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'реєстрація') XXXXXXXXX
      XXXXXXX

      BB BBBXX XXXXXXXXXXXXXXXXXXFFFFXXXXBBBBB

      XXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBXX gettext(u'війти') XXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'головна сторінка') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB