# Generated by Django 5.2.9 on 2026-01-29 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('hide_email', models.BooleanField(default=False)),
                ('hide_phone', models.BooleanField(default=False)),
                ('hide_telegram', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('verification_status', models.CharField(choices=[('unverified', 'Не верифицирован'), ('verified_user', 'Проверенный пользователь'), ('verified_student', 'Проверенный студент'), ('verified_employer', 'Проверенный работодатель')], default='unverified', max_length=20)),
                ('email_verified', models.CharField(choices=[('unverified', 'Не верифицирован'), ('verified_email', 'Верифицированый')], default='unverified', max_length=30)),
                ('email_verification_token', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Группы, к которым относится пользователь', related_name='profile_set', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Права пользователя', related_name='profile_set', to='auth.permission', verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Профили',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
