# Generated by Django 5.2.9 on 2026-03-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hide_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hide_telegram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_username',
        ),
    ]
