# Generated by Django 5.2.9 on 2026-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_hide_email_remove_profile_hide_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_user',
            field=models.BooleanField(default=False),
        ),
    ]
