# Generated by Django 5.2.9 on 2026-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('bratislava', 'Bratislava'), ('kosice', 'Košice'), ('zilina', 'Žilina'), ('trnava', 'Trnava'), ('nitra', 'Nitra')], max_length=50),
        ),
    ]
