# Generated by Django 5.2.9 on 2026-03-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
