# Generated by Django 5.2.9 on 2026-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('bratislava', 'Братіслава'), ('kosice', 'Košice'), ('zilina', 'Žilina'), ('trnava', 'Trnava'), ('nitra', 'Nitra')], max_length=50),
        ),
    ]
