# Generated by Django 5.2.9 on 2026-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_city'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профілі', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('bratislava', 'Братіслава'), ('kosice', 'Кошици'), ('trnava', 'Трнава'), ('presov', 'Прешов')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Групи, до яких належить користувач', related_name='profile_set', to='auth.group', verbose_name='Групи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Права користувача', related_name='profile_set', to='auth.permission', verbose_name='Права'),
        ),
    ]
