BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
BBBBB BBBBB
    XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX gettext(u'Будь ласка, увійдіть до облікового запису або зареєструйтесь') XXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'вхід') XXXX
                XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'реєстрація') XXXX
            XXXXXX
        XXXXXX
    XXXXXX


BBBBBBBB