# Generated by Django 5.2.9 on 2026-01-29 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('process', 'В процессе'), ('agree', 'Разрешено'), ('denied', 'Отказано')], default='process', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Верификация',
                'verbose_name_plural': 'Верификации',
            },
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('verification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.verification')),
            ],
            bases=('profiles.verification',),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('verification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.verification')),
                ('ico', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ICO должно состоять из 8 цифр', regex='^\\d{8}$')])),
                ('company_name', models.CharField(max_length=150)),
            ],
            bases=('profiles.verification',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('verification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.verification')),
            ],
            bases=('profiles.verification',),
        ),
    ]
