# Generated by Django 5.2.9 on 2026-03-22 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tglinkcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name': 'Верифікації', 'verbose_name_plural': 'Верифікації'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='ico',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ICO має складатися з 8 цифр', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('process', 'в процесі'), ('agree', 'дозволено'), ('denied', 'відмовлено')], default='process', max_length=10),
        ),
    ]
