# Generated by Django 5.2.9 on 2026-04-30 16:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_verification_options_alter_employer_ico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tglinkcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram link code', 'verbose_name_plural': 'Telegram link codes'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name': 'Verification', 'verbose_name_plural': 'Verifications'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='ico',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ICO must consist of 8 digits', regex='^\\d{8}$')], verbose_name='ICO'),
        ),
        migrations.AlterField(
            model_name='tglinkcode',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='tglinkcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tglinkcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='tglinkcode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='tglinkcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('process', 'In progress'), ('agree', 'Approved'), ('denied', 'Denied')], default='process', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
