# Generated by Django 5.2.9 on 2026-01-29 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('slug_title', models.SlugField(blank=True, max_length=120)),
                ('text', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('Kosice', 'Кошице'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава')], max_length=20)),
                ('source_telegram', models.BooleanField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('caseType', models.CharField(blank=True, choices=[('forAdmin', 'Для админа'), ('findJob', 'Ищу роботу'), ('giveJob', 'Предлагаю роботу')], max_length=15, null=True)),
                ('telegram_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('employment_type', models.CharField(blank=True, choices=[('any', 'Любая'), ('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('contract', 'Контракт'), ('temp', 'Временная'), ('intern', 'Стажировка')], default='any', max_length=20, null=True)),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_period', models.CharField(blank=True, choices=[('hour', 'В час'), ('day', 'В день'), ('month', 'В месяц')], default='month', max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('private_status', models.CharField(choices=[('common', 'обычное'), ('top', 'топ')], default='common', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('slug_title', models.SlugField(blank=True, max_length=120)),
                ('text', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('Kosice', 'Кошице'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава')], max_length=20)),
                ('source_telegram', models.BooleanField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('caseType', models.CharField(blank=True, choices=[('forAdmin', 'Для админа'), ('findNeighbor', 'Ищу соседа'), ('offer_room', 'Предлагаю жильё')], max_length=30, null=True)),
                ('telegram_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('count_neighbors', models.IntegerField(blank=True, default=None, null=True)),
                ('my_gender', models.IntegerField(choices=[(0, 'Любой'), (1, 'Мужской'), (2, 'Женский')], default=0)),
                ('neighbor_gender', models.IntegerField(choices=[(0, 'Любой'), (1, 'Мужской'), (2, 'Женский')], default=0)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, default=16, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('budget', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_period', models.CharField(blank=True, choices=[('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default='month', max_length=10)),
                ('housing_type', models.CharField(blank=True, choices=[('room', 'Комната'), ('flat', 'Квартира'), ('dormitory', 'Общежитие')], max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=10)),
                ('private_status', models.CharField(choices=[('common', 'обычное'), ('top', 'топ')], default='common', max_length=50)),
                ('my_lifestyles', models.ManyToManyField(blank=True, related_name='my_posts', to='ads.lifestyle')),
                ('neighbor_lifestyles', models.ManyToManyField(blank=True, related_name='neighbor_posts', to='ads.lifestyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeighborPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='neighbor/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.neighborpost')),
            ],
        ),
        migrations.CreateModel(
            name='ThingsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('slug_title', models.SlugField(blank=True, max_length=120)),
                ('text', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('Kosice', 'Кошице'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава')], max_length=20)),
                ('source_telegram', models.BooleanField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('caseType', models.CharField(blank=True, choices=[('forAdmin', 'Для админа'), ('sell_category', 'Продать'), ('buy_category', 'Купить'), ('free_category', 'Безплатно')], max_length=50, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('has_photo', models.BooleanField(blank=True, default=None, null=True)),
                ('telegram_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новое'), ('used', 'Б/У')], max_length=4, null=True)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('none', 'ничего'), ('bicycles', 'велосипед'), ('auto', 'Машина'), ('child', 'Дети'), ('pc', 'ПК'), ('phone', 'телефон')], max_length=50, null=True)),
                ('private_status', models.CharField(choices=[('common', 'обычное'), ('top', 'топ')], default='common', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThingsPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='things/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.thingspost')),
            ],
        ),
    ]
