# Generated by Django 5.2.9 on 2026-01-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingspost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
