# Generated by Django 5.2.9 on 2026-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_thingspost_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
