# Generated by Django 5.2.9 on 2026-01-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_jobpost_photo_id_neighborpost_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='has_photo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='has_photo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
