# Generated by Django 5.2.9 on 2026-02-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_jobpost_chat_id_jobpost_has_photo_jobpost_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='tg_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='tg_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='tg_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
