# Generated by Django 5.2.9 on 2026-02-14 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_jobpost_tg_deleted_neighborpost_tg_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='things_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
