# Generated by Django 5.2.9 on 2026-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_jobpost_user_alter_neighborpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
