# Generated by Django 5.2.9 on 2026-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_jobpost_created_ip_neighborpost_created_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('pending', 'Ожидание'), ('closed', 'Закрыто')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('pending', 'Ожидание'), ('closed', 'Закрыто')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('pending', 'Ожидание'), ('closed', 'Закрыто')], default='pending', max_length=20),
        ),
    ]
