# Generated by Django 5.2.9 on 2026-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_category_remove_thingspost_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='my_age',
            field=models.PositiveSmallIntegerField(blank=True, default=16, null=True),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'Будь яке житло'), ('room', 'Комната'), ('flat', 'Квартира'), ('dormitory', 'Общежитие')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('any', 'Не відомий період'), ('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default='any', max_length=10),
        ),
    ]
