# Generated by Django 5.2.9 on 2026-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_neighborpost_my_age_alter_neighborpost_housing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'для адміна'), ('findJob', 'шукаю роботу'), ('giveJob', 'пропуную роботу')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('any', 'будь-яка'), ('full', 'повна занятість'), ('part', 'часткова занятість'), ('contract', 'контракт'), ('temp', 'тимчасова'), ('intern', 'стажування')], default='any', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='private_status',
            field=models.CharField(choices=[('common', 'звичайне'), ('top', 'топ')], default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('hour', 'в годину'), ('day', 'в день'), ('month', 'в місяцт')], default='month', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'активно'), ('pending', 'очікування'), ('closed', 'закрито')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'для адміна'), ('findNeighbor', 'шукаю сусіда')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'будь яке житло'), ('room', 'кімната'), ('flat', 'квартира'), ('dormitory', 'гуртожиток')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_gender',
            field=models.IntegerField(choices=[(0, 'будь-який'), (1, 'чоловічий'), (2, 'жіночий')], default=0),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='neighbor_gender',
            field=models.IntegerField(choices=[(0, 'будь-який'), (1, 'чоловічий'), (2, 'жіночий')], default=0),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='private_status',
            field=models.CharField(choices=[('common', 'звичайне'), ('top', 'топ')], default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('any', 'не відомий період'), ('day', 'день'), ('week', 'неділя'), ('month', 'місяць'), ('year', 'рік')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='status',
            field=models.CharField(choices=[('active', 'активно'), ('pending', 'очікування'), ('closed', 'закрито')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'для адміна'), ('sell_category', 'продати'), ('buy_category', 'купити'), ('free_category', 'безкоштовно')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'нове'), ('used', 'Б/У')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='private_status',
            field=models.CharField(choices=[('common', 'звичайне'), ('top', 'топ')], default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='status',
            field=models.CharField(choices=[('active', 'активно'), ('pending', 'очікування'), ('closed', 'закрито')], default='pending', max_length=20),
        ),
    ]
