# Generated by Django 5.2.9 on 2026-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_jobpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='withoutRegister',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='withoutRegister',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='withoutRegister',
            field=models.BooleanField(default=False),
        ),
    ]
