# Generated by Django 5.2.9 on 2026-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_jobpost_withoutregister_neighborpost_withoutregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Tavava', 'трнава')], max_length=20),
        ),
    ]
