# Generated by Django 5.2.9 on 2026-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_jobpost_city_alter_neighborpost_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('hour', 'в годину'), ('month', 'в місяць'), ('day', 'в день'), ('week', 'в тиждень')], default='month', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_gender',
            field=models.IntegerField(choices=[(0, 'невизначена стать'), (1, 'чоловічий'), (2, 'жіночий')], default=0),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='neighbor_gender',
            field=models.IntegerField(choices=[(0, 'невизначена стать'), (1, 'чоловічий'), (2, 'жіночий')], default=0),
        ),
    ]
