# Generated by Django 5.2.9 on 2026-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_jobpost_salary_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingspost',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
