# Generated by Django 5.2.9 on 2026-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_alter_category_slug_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
