# Generated by Django 5.2.9 on 2026-03-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_jobpost_preview_image_neighborpost_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
