# Generated by Django 5.2.9 on 2026-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_jobpost_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('будь яке житло', 'Any'), ('кімната', 'Room'), ('квартира', 'Apartment'), ('гуртожиток', 'Dorm')], default='будь яке житло', max_length=20),
        ),
    ]
