# Generated by Django 5.2.9 on 2026-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_alter_neighborpost_housing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('будь-яке місто', 'Any'), ('Кошици', 'Kosice'), ('Прешов', 'Presov'), ('Братіслава', 'Bratislava'), ('трнава', 'Trnava')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('будь-яке місто', 'Any'), ('Кошици', 'Kosice'), ('Прешов', 'Presov'), ('Братіслава', 'Bratislava'), ('трнава', 'Trnava')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('не відомий період', 'Any'), ('день', 'Day'), ('неділя', 'Week'), ('місяць', 'Month'), ('рік', 'Year')], default='не відомий період', max_length=50),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('будь-яке місто', 'Any'), ('Кошици', 'Kosice'), ('Прешов', 'Presov'), ('Братіслава', 'Bratislava'), ('трнава', 'Trnava')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('нове', 'New'), ('Б/У', 'Used')], max_length=4, null=True),
        ),
    ]
