# Generated by Django 5.2.9 on 2026-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_alter_jobpost_city_alter_neighborpost_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'будь-яке житло'), ('room', 'кімната'), ('apartment', 'квартира'), ('dorm', 'гуртожиток')], default='any', max_length=20),
        ),
    ]
