# Generated by Django 5.2.9 on 2026-04-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_alter_neighborpost_housing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('any', 'не відомий період'), ('day', 'день'), ('week', 'неділя'), ('month', 'місяць'), ('year', 'рік')], default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'нове'), ('not new', 'Б/У')], max_length=25, null=True),
        ),
    ]
