# Generated by Django 5.2.9 on 2026-04-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0024_alter_jobpost_telegram_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='neighborpost',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='thingspost',
            name='phone',
        ),
    ]
