# Generated by Django 5.2.9 on 2026-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_remove_jobpost_phone_remove_neighborpost_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_sk',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title_sk',
        ),
    ]
