# Generated by Django 5.2.9 on 2026-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_remove_category_title_sk_remove_subcategory_title_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
