# Generated by Django 5.2.9 on 2026-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0027_jobpost_source_facebook_neighborpost_source_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
