# Generated by Django 5.2.9 on 2026-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_jobpost_link_facebook_neighborpost_link_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Trnava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'для адміна'), ('findNeighbor', 'шукаю сусіда'), ('rent', 'шукаю квартиру')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Trnava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('any', 'будь-яке місто'), ('Kosice', 'Кошици'), ('Presov', 'Прешов'), ('Bratislava', 'Братіслава'), ('Trnava', 'трнава')], max_length=20),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('used', 'Б/У')], max_length=25, null=True),
        ),
    ]
