# Generated by Django 5.2.9 on 2026-04-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_alter_jobpost_city_alter_neighborpost_casetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'для адміна'), ('findNeighbor', 'шукаю сусіда'), ('rent', 'оренда квартири')], max_length=30, null=True),
        ),
    ]
