# Generated by Django 5.2.9 on 2026-04-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0030_alter_neighborpost_casetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'нове'), ('used', 'Б/У')], max_length=25, null=True),
        ),
    ]
