# Generated by Django 5.2.9 on 2026-04-30 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_alter_thingspost_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': 'Job post', 'verbose_name_plural': 'Job posts'},
        ),
        migrations.AlterModelOptions(
            name='jobpostimage',
            options={'verbose_name': 'Job post image', 'verbose_name_plural': 'Job post images'},
        ),
        migrations.AlterModelOptions(
            name='neighborpost',
            options={'verbose_name': 'Neighbor post', 'verbose_name_plural': 'Neighbor posts'},
        ),
        migrations.AlterModelOptions(
            name='neighborpostimage',
            options={'verbose_name': 'Neighbor post image', 'verbose_name_plural': 'Neighbor post images'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='thingspost',
            options={'verbose_name': 'Things post', 'verbose_name_plural': 'Things posts'},
        ),
        migrations.AlterModelOptions(
            name='thingspostimage',
            options={'verbose_name': 'Things post image', 'verbose_name_plural': 'Things post images'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'For admin'), ('findJob', 'Looking for a job'), ('giveJob', 'Offering a job')], max_length=15, null=True, verbose_name='Case type'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('any', 'Any city'), ('Kosice', 'Kosice'), ('Presov', 'Presov'), ('Bratislava', 'Bratislava'), ('Trnava', 'Trnava')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Created IP'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Email token'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('full', 'Full-time'), ('part', 'Part-time'), ('contract', 'Contract'), ('temp', 'Temporary'), ('intern', 'Internship')], default='any', max_length=20, null=True, verbose_name='Employment type'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='has_photo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Has photo'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo ID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='private_status',
            field=models.CharField(choices=[('common', 'Common'), ('top', 'Top')], default='common', max_length=50, verbose_name='Private status'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary from'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('hour', 'Per hour'), ('month', 'Per month'), ('day', 'Per day'), ('week', 'Per week')], default='month', max_length=10, null=True, verbose_name='Salary period'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary to'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Slug title'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Facebook'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='source_telegram',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Telegram'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Telegram code'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tg_deleted',
            field=models.BooleanField(default=False, verbose_name='Telegram deleted'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='withoutRegister',
            field=models.BooleanField(default=False, verbose_name='Without registration'),
        ),
        migrations.AlterField(
            model_name='jobpostimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='jobpostimage',
            name='image',
            field=models.ImageField(upload_to='job/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='jobpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.jobpost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'For admin'), ('findNeighbor', 'Looking for a roommate'), ('rent', 'Apartment rent')], max_length=30, null=True, verbose_name='Case type'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('any', 'Any city'), ('Kosice', 'Kosice'), ('Presov', 'Presov'), ('Bratislava', 'Bratislava'), ('Trnava', 'Trnava')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='count_neighbors',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of neighbors'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Created IP'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Email token'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='has_photo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Has photo'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'Any housing'), ('room', 'Room'), ('apartment', 'Apartment'), ('dorm', 'Dormitory')], default='any', max_length=20, verbose_name='Housing type'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Maximum age'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, default=16, null=True, verbose_name='Minimum age'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='move_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Move-in date'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_age',
            field=models.PositiveSmallIntegerField(blank=True, default=16, null=True, verbose_name='My age'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_gender',
            field=models.IntegerField(choices=[(0, 'Undefined gender'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='My gender'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_lifestyles',
            field=models.ManyToManyField(blank=True, related_name='my_posts', to='ads.lifestyle', verbose_name='My lifestyles'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='neighbor_gender',
            field=models.IntegerField(choices=[(0, 'Undefined gender'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Neighbor gender'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='neighbor_lifestyles',
            field=models.ManyToManyField(blank=True, related_name='neighbor_posts', to='ads.lifestyle', verbose_name='Neighbor lifestyles'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo ID'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='private_status',
            field=models.CharField(choices=[('common', 'Common'), ('top', 'Top')], default='common', max_length=50, verbose_name='Private status'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('any', 'Unknown period'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='any', max_length=50, verbose_name='Rent period'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Slug title'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Facebook'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='source_telegram',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Telegram'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Telegram code'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='tg_deleted',
            field=models.BooleanField(default=False, verbose_name='Telegram deleted'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor_posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='withoutRegister',
            field=models.BooleanField(default=False, verbose_name='Without registration'),
        ),
        migrations.AlterField(
            model_name='neighborpostimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='neighborpostimage',
            name='image',
            field=models.ImageField(upload_to='neighbor/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='neighborpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.neighborpost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ads.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title_uk',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'For admin'), ('sell_category', 'Sell'), ('buy_category', 'Buy'), ('free_category', 'Free')], max_length=50, null=True, verbose_name='Case type'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('any', 'Any city'), ('Kosice', 'Kosice'), ('Presov', 'Presov'), ('Bratislava', 'Bratislava'), ('Trnava', 'Trnava')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=25, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Created IP'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email confirmed'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Email token'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='has_photo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Has photo'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is verified'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='link_facebook',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Message ID'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='photo_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo ID'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='preview_image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='private_status',
            field=models.CharField(choices=[('common', 'Common'), ('top', 'Top')], default='common', max_length=50, verbose_name='Private status'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Slug title'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='source_facebook',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Facebook'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='source_telegram',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Telegram'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='things', to='ads.subcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Telegram code'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='tg_deleted',
            field=models.BooleanField(default=False, verbose_name='Telegram deleted'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='things_posts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='withoutRegister',
            field=models.BooleanField(default=False, verbose_name='Without registration'),
        ),
        migrations.AlterField(
            model_name='thingspostimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='thingspostimage',
            name='image',
            field=models.ImageField(upload_to='things/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='thingspostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.thingspost', verbose_name='Post'),
        ),
    ]
