# Generated by Django 5.2.9 on 2026-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_alter_category_options_alter_jobpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text_en'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title_en'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text_en'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title_en'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text_en'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title_en'),
        ),
    ]
