# Generated by Django 5.2.9 on 2026-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_jobpost_text_en_jobpost_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title_en'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title_en'),
        ),
    ]
