# Generated by Django 5.2.9 on 2026-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_category_title_en_subcategory_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('any', 'Будь-яке місто'), ('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('any', 'Будь-яке місто'), ('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'будь-яке житло'), ('room', 'кімнату'), ('apartment', 'квартиру'), ('dorm', 'гуртожиток')], default='any', max_length=20, verbose_name='Housing type'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='my_gender',
            field=models.IntegerField(choices=[(0, 'невизначана стать'), (1, 'чоловічий'), (2, 'жіночий')], default=0, verbose_name='My gender'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='neighbor_gender',
            field=models.IntegerField(choices=[(0, 'невизначана стать'), (1, 'чоловічий'), (2, 'жіночий')], default=0, verbose_name='Neighbor gender'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='rent_period',
            field=models.CharField(choices=[('any', 'будь який період'), ('day', 'день'), ('week', 'неділю'), ('month', 'місяць'), ('year', 'рік')], default='any', max_length=50, verbose_name='Rent period'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'For admin'), ('sell_category', 'продаж'), ('buy_category', 'купівля'), ('free_category', 'безскоштовно')], max_length=50, null=True, verbose_name='Case type'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('any', 'Будь-яке місто'), ('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'нове'), ('used', 'б/У')], max_length=25, null=True, verbose_name='Condition'),
        ),
    ]
