# Generated by Django 5.2.9 on 2026-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_alter_jobpost_city_alter_neighborpost_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_sk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title sk'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_sk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title sk'),
        ),
    ]
