# Generated by Django 5.2.9 on 2026-05-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0036_category_title_sk_subcategory_title_sk'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='text_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Text_sk'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='title_sk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title_sk'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='text_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Text_sk'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='title_sk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title_sk'),
        ),
    ]
