# Generated by Django 5.2.9 on 2026-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0037_neighborpost_text_sk_neighborpost_title_sk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rooms'),
        ),
    ]
