# Generated by Django 5.2.9 on 2026-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0038_neighborpost_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborpost',
            name='rooms',
            field=models.FloatField(blank=True, null=True, verbose_name='Rooms'),
        ),
    ]
