# Generated by Django 5.2.9 on 2026-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0039_alter_neighborpost_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава'), ('Zilina', 'Жиліна'), ('Nitra', 'Нітра'), ('Trencin', 'Тренчин'), ('Banska-bristrica', 'Банска-Бистрица'), ('Poprad', 'Попрад')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава'), ('Zilina', 'Жиліна'), ('Nitra', 'Нітра'), ('Trencin', 'Тренчин'), ('Banska-bristrica', 'Банска-Бистрица'), ('Poprad', 'Попрад')], max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='thingspost',
            name='city',
            field=models.CharField(choices=[('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава'), ('Zilina', 'Жиліна'), ('Nitra', 'Нітра'), ('Trencin', 'Тренчин'), ('Banska-bristrica', 'Банска-Бистрица'), ('Poprad', 'Попрад')], max_length=20, verbose_name='City'),
        ),
    ]
