# Generated by Django 5.2.9 on 2026-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0040_alter_jobpost_city_alter_neighborpost_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='id_bazos',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Bazos ID'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='img_bazos',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Image Bazos'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='link_bazos',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Link Bazos'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='source_bazos',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Bazos'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='id_bazos',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Bazos ID'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='img_bazos',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Image Bazos'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='link_bazos',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Link Bazos'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='source_bazos',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Source Bazos'),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='caseType',
            field=models.CharField(blank=True, choices=[('forAdmin', 'For admin'), ('findNeighbor', 'шукаю сусіда'), ('rent', 'оренда')], max_length=30, null=True, verbose_name='Case type'),
        ),
    ]
