# Generated by Django 5.2.9 on 2026-06-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0041_neighborpost_id_bazos_neighborpost_img_bazos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingspost',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='thingspost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='things', to='ads.category', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
