# Generated by Django 5.2.9 on 2026-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0042_remove_thingspost_subcategory_thingspost_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='source_facebook',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='source_telegram',
        ),
        migrations.RemoveField(
            model_name='neighborpost',
            name='source_bazos',
        ),
        migrations.RemoveField(
            model_name='neighborpost',
            name='source_facebook',
        ),
        migrations.RemoveField(
            model_name='neighborpost',
            name='source_telegram',
        ),
        migrations.RemoveField(
            model_name='thingspost',
            name='source_bazos',
        ),
        migrations.RemoveField(
            model_name='thingspost',
            name='source_facebook',
        ),
        migrations.RemoveField(
            model_name='thingspost',
            name='source_telegram',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Source'),
        ),
    ]
