# Generated by Django 5.2.9 on 2026-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0043_remove_jobpost_source_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='deposit',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Deposit'),
        ),
    ]
