# Generated by Django 5.2.9 on 2026-06-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0044_neighborpost_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingspost',
            name='category',
            field=models.ForeignKey(blank=True, db_column='productCategory', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='things', to='ads.category', verbose_name='Category'),
        ),
    ]
