# Generated by Django 5.2.9 on 2026-07-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0045_alter_thingspost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad ID'),
        ),
    ]
