# Generated by Django 5.2.9 on 2026-07-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0046_neighborpost_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promoted until'),
        ),
        migrations.AddField(
            model_name='neighborpost',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promoted until'),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promoted until'),
        ),
    ]
