# Generated by Django 5.2.9 on 2026-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0047_jobpost_promoted_until_neighborpost_promoted_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_uk', models.ImageField(null=True, upload_to='banners/uk/')),
                ('image_en', models.ImageField(null=True, upload_to='banners/en/')),
                ('image_sk', models.ImageField(null=True, upload_to='banners/sk/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField()),
                ('alt_uk', models.CharField(max_length=150, null=True)),
                ('alt_en', models.CharField(max_length=150, null=True)),
                ('alt_sk', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
