# Generated by Django 5.2.9 on 2026-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0048_advertisingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='name_sk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='lifestyle',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
    ]
