# Generated by Django 5.2.9 on 2026-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0049_lifestyle_name_en_lifestyle_name_sk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingspost',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'нове'), ('used', 'б/У'), ('normal', 'нормальний'), ('like_new', 'як нове'), ('bad', 'поганий')], max_length=25, null=True, verbose_name='Condition'),
        ),
    ]
