# Generated by Django 5.2.9 on 2026-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0050_alter_thingspost_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adress'),
        ),
    ]
