# Generated by Django 5.2.9 on 2026-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0051_neighborpost_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborpost',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thingspost',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='neighborpost',
            name='housing_type',
            field=models.CharField(choices=[('any', 'будь-яке житло'), ('room', 'кімната'), ('apartment', 'квартира'), ('dorm', 'гуртожиток')], default='any', max_length=20, verbose_name='Housing type'),
        ),
    ]
