# Generated by Django 5.2.9 on 2026-03-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_favorite_uniq_fav_user_type_obj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
