# Generated by Django 5.2.9 on 2026-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions', '0003_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='telegram')),
                ('city', models.CharField(choices=[('Kosice', 'Кошиця'), ('Presov', 'Прешов'), ('Bratislava', 'Братислава'), ('Trnava', 'Трнава'), ('Zilina', 'Жиліна'), ('Nitra', 'Нітра'), ('Trencin', 'Тренчин'), ('Banska-bristrica', 'Банска-Бистрица'), ('Poprad', 'Попрад')], default='Bratislava', max_length=100, verbose_name='city')),
                ('type_rent', models.CharField(choices=[('forAdmin', 'For admin'), ('findNeighbor', 'шукаю сусіда'), ('rent', 'оренда')], default='rent', max_length=100, verbose_name='type')),
                ('type_things', models.CharField(choices=[('forAdmin', 'For admin'), ('sell_category', 'продаж'), ('buy_category', 'купівля'), ('free_category', 'безскоштовно')], default='sell_category', max_length=100, verbose_name='type')),
                ('price', models.FloatField(verbose_name='price')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='category')),
                ('budget_from', models.IntegerField(blank=True, null=True, verbose_name='budget from')),
                ('budget_to', models.IntegerField(blank=True, null=True, verbose_name='budget from')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='rooms')),
                ('last_checked_id', models.IntegerField(blank=True, null=True, verbose_name='last checked id')),
            ],
        ),
    ]
