# Generated by Django 5.2.9 on 2026-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_rent',
            field=models.CharField(blank=True, choices=[('findNeighbor', 'find neighbor'), ('rent', 'rent')], max_length=100, null=True),
        ),
    ]
