# Generated by Django 5.2.9 on 2026-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_alter_notification_type_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
