# Generated by Django 5.2.9 on 2026-07-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_alter_notification_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='telegram',
        ),
    ]
