# Generated by Django 5.2.9 on 2026-07-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_remove_notification_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='price',
        ),
    ]
