# Generated by Django 5.2.9 on 2026-07-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0047_jobpost_promoted_until_neighborpost_promoted_until_and_more'),
        ('interactions', '0008_remove_notification_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.category', verbose_name='category'),
        ),
    ]
