# Generated by Django 5.2.9 on 2026-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_alter_notification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type_rent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_things',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('findNeighbor', 'find neighbor'), ('rent', 'rent'), ('sell_category', 'sell'), ('buy_category', 'buy')], max_length=100, null=True),
        ),
    ]
