# Generated by Django 5.2.9 on 2026-07-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0010_remove_notification_type_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('findNeighbor', 'шукаю сусіда'), ('rent', 'оренда'), ('sell_category', 'купівля'), ('buy_category', 'продаж')], max_length=100, null=True),
        ),
    ]
