# Generated by Django 5.2.9 on 2026-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('findNeighbor', 'find neighbor'), ('rent', 'rent'), ('sell_category', 'sell'), ('buy_category', 'buy')], max_length=100, null=True),
        ),
    ]
