BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX gettext(u'зміна оголошення') XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX gettext(u'редагування оголошення') XXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        XXXX XXXXXXX XXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            
        XXXXXX

        XXXX XXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'поточні зображення') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BBB BBB BB BBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXX XXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                             gettext(u'видалити') 
                        XXXXXXXX
                    XXXXXX
                BBBBB
                    XX XXXXXXXXXXXXXXXXXXX gettext(u'немає зображень') XXXX
                BBBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'додати зображення') XXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX gettext(u'зберегти зміни') XXXXXXXXX
        XXXXXX
    XXXXXXX
XXXXXX

BBBBBBBB