BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX gettext(u'верифікація роботодавця') XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'верифікація роботодавця') XXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'заповніть дані компанії, щоб підтвердити статус роботодавця.') 
        XXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            BBBBB

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'надіслати на перевірку') 
            XXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB