BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBB

XXXXXXX gettext(u'мій профіль') XXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X

    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X

        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXX

        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X X XXXXXX

        XXXXX XXXX X XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXX XXXXX
        XX

        XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

XXX
XXXXXXXXX
XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                    XXXX XXXXXX XXXXXXXXXXXXXXX
                BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXX gettext(u'на платформі з')   X XXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'email веріфікован') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений користувач') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений студент') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений роботодавець') XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'поділитися профілем') XXXX
                XX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX gettext(u'вийти з аккаунту') XXXX
            XXXXXX
        XXXXXX


        XXXX XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                BBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXX
                     gettext(u'відновити оголошення за email') 
                XXXXXXXXX
            XXXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'змінити профіль') 
            XXXXXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'пройти верифікацію') 
            XXXXXXXXX

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBXXX
                XXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
                    XXXXX XXXXXXXX XXXXXX X X X XXXXXXXXXXXX
                XXXXXX
                 gettext(u'купити рекламу') 
            XXXXXXXXX

            XXXXXXX
            XXXXXXXXXXXXXXXXXXXX X
                XXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXX
                XXXX XXXX
                XXXXXXXX XXXX XXXXX
                XXXXXXXXXXX XXXXXXXX
                XXXXXX XXXXXX XX XXXXX XXXXX XXXXXXXXXX XXXX XX
                XXXXXXXXXXXX XXXX
                XXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXX XXXXXX
                XXXXXXX XXXXX XXXXX XXXXXXXX
                XXXXXXXXXXXXXX XXXXX
                XXXXXXX XXXXXXXX
                XXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXX XXXXX XXXXXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX
                XXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX
            X

            XXXXXXXXXX XXXXXXXXXXXXX X
                XXX XXXX X
                    XXXXXXXXXXX X X X X XXXXXXXX XXX XXXX XXXXXX
                X
                XXX X
                    XXXXXXXXXXX X X X XXX XXXXXXXX XXX XXXX XXX
                X
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXX XXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXX X XXX XXXX XXXXXXXX XXX XXXX XXXXX
                XXXXXX XXXXXX
            X



            XXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXX XXXXXXXXXXXXXX
            X
            XXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX gettext(u'редагування профілю') XXXXX
                    XXX gettext(u'оновіть основну інформацію вашого профілю') XXXX
                XXXXXX

                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                             gettext(u'зберегти зміни') 
                        XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX




        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX gettext(u'Верифікація') XXXXX
                XX XXXXXXXXXXXXXXXXX gettext(u'оберіть тип верифікації') XXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'👤 користувач') XXXXX
                        XXX gettext(u'підтвердження особистого профілю') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX
                             gettext(u'пройти') 
                        XXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX gettext(u'🎓 студент') XXXXX
                        XXX gettext(u'підтвердження студентського статусу') XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX
                             gettext(u'пройти') 
                        XXXX
                    XXXXXX

                    XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                    XXXX    XXXX gettext(u'💼 роботодавець') XXXXX XXX
                    XXXX    XXX gettext(u'підтвердження компанії або бізнесу') XXXX XXX
                    XXXX    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXX
                    XXXX         gettext(u'пройти')  XXX
                    XXXX    XXXX XXX
                    XXXXXXXXXX XXX

                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                     gettext(u'Реклама на Pusto.sk') 
                XXXXX

                XXX
                     gettext(u'Наразі придбати рекламу можна напряму через адміністратора Telegram.') 
                XXXX

                XX XXXXXXXXXXXXXXXXXX XXXXXXX
                     gettext(u'Для замовлення реклами звертайтесь:') 
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX

                XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
                     gettext(u'Ми допоможемо підібрати формат реклами та відповімо на всі запитання.') 
                XXXX
            XXXXXX
        XXXXXX
XXXXXX

XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXX gettext(u'мої оголошення') XXXXX

  BB BBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX gettext(u'всі оголошення') XXXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB B B
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXX
              BBB BBBB BB BBBBBBBBB


                    XXXX XXXXXXXXXXXXXX

                        BB BBBBBBBBBBBBBBBBBB
                          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBBB
                          XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB
                          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXX gettext(u'зібрано з Telegram') XXXX
                            XXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBB BB BBBBB
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                            XXXXXX
                        BBBBB
                        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

                        BB BBBBBBBBBBBBBBBBBBBB
                          XXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBB BB BBBB
                              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                            BBBB
                              FFFFFFFFFFFFFFFFFF
                            BBBBB
                          XXXXX
                        BBBB
                          XXXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBB
                               X
                            BBBB BBBBBBBBBBB
                               X
                            BBBB BBBBBBBBBBBBBBBB
                              BB BBBBBBBBBBBBBB X BBBBB X
                            BBBB
                              
                            BBBBB
                          XXXXXX

                          XXX XXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBB BB BBBB
                              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                            BBBB
                              FFFFFFFFFFFFFFFFFF
                            BBBBB
                          XXXXX
                        BBBBB

                      XXXX XXXXXXXXXXXXX
                        FFFFFFFFFFF FFFF
                      XXXXXX

                      XXXX XXXXXXXXXXXXXXXXXXXXX
                          BB BBBBBBBBBBBBBBBBBBB BB BBBBB
                            XXXXXXX
                                XXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX
                            X
                                 gettext(u'підняти') 
                            XXXXXXXXX
                          BBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                           gettext(u'редагувати') 
                        XXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX
                           XXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Ви впевнені, що хочете видалити це оголошення?') XXXX
                           XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                           gettext(u'видалити') 
                        XXXX
                      XXXXXX
                    XXXXXX
              BBBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Закрити') XX
                        XXXXXXX
                    XXXXXXXXX

                    XXXX XXX XX XXXXX XXXXXX XXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Просування оголошення') XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             gettext(u'Оберіть тривалість підняття. Ваше оголошення отримає більше видимості у списку.') 
                        XXXX

                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Старт') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'3 дні') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                     gettext(u'Швидке підняття оголошення для короткого просування.') 
                                XXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Обрати') XXXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Популярний') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'7 днів') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                     gettext(u'Оптимальний варіант для більш стабільного просування.') 
                                XXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Обрати') XXXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Максимум') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'14 днів') XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                     gettext(u'Найкраще рішення для довшого та помітнішого розміщення.') 
                                XXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Обрати') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXX XX XXXXX XXXXXXX XXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXX  gettext(u'Змінити тариф') 
                        XXXXXXXXX

                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Спосіб оплати') XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     gettext(u'Крипта') 
                                XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XX XXXXXXXXXXXXX
                                XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     gettext(u'Картка UA') 
                                XXXXXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                         gettext(u'Email, Telegram (@нік) або телефон') 
                                    XXXXXXXX
                                    XXXXXX
                                        XXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXX
                                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXXXXXXXX gettext(u'Наприклад: user@mail.com або @username') X
                                        XXXXXXXX
                                    X
                                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                         gettext(u"Адміністратор зв'яжеться з вами для оплати цим способом.") 
                                    XXXX

                                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

                                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                         gettext(u'Надіслати запит') 
                                    XXXXXXXXX
                                XXXXXXX

                                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXX gettext(u"Дякуємо! Очікуйте, адміністратор незабаром зв'яжеться з вами.") XXXX
                                XXXXXX
                            XXXXXX

                            XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXX XXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                 gettext(u'Оплатити криптою') 
                            XXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB B B
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXX XXX XXX XX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXX XXX XXX XX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBBB
      XXXXXX
    XXXXXXXXXX
  BBBB
    XXXX XXXXXXXXXXXXXXXXXX gettext(u'у вас поки що немає оголошень') XXXXXX
  BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u"код прив'язки Telegram:") XXXXXXX

        XXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            
        XXXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'згенерувати заново') 
        XXXXXXXXX
    XXXXXX

    XXXX  XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX gettext(u'діє до:') XXXXXXX
        XXXXX XXXXXXXXXXXXXXFFFFFFFFFFF FFFFFFXXXXXXX
    XXXXXX
    XXXXXX
XXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XX XXXXX XX XXXXXX XXXXXXX

    XXXXXXXX XXXXXXX
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXX X XXXXXXXXXXXXXXXX X XX X XXXX
    X

    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXXXXXXXXXXX
XXX
XXXXXXXXX

XXXXXXXX
XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XX X
    XXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX X
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Посилання скопійовано!') XXX
    X XXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXX
    X
XXX
XXXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
X

XXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXX XXXXXXX

  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXX XXX X X XXXXXXX XXXXXXXXX XXXXX XXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXX XX XXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX X
    XXX X X XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      X X XXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX X XXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
    XXX
    XXXXXX XX
  X

  XXX XXXXXXXXXXXXXXXX X XXXXX
  XXX XXXXXXXXXXXXX X XXXXX
  XXX XXXXXXXXXXXXX X XXX

  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXX X XXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXX

  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

  XX XXX XXX XX XXXXX XXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
      XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXX
    XXX
  XXX

  XX XXX XXX XX XXXXXXXXXXXXX XXXXXXX XXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

      XX XXXXXXX XXX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      X
    XXX
  XXX

  XX XXX XXXXXX XXXXXXXXXXXXXX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XX XXXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX

        XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX
          XBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
          X XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XX
          XX XX XXXXXXXXXXXXXXXXXXXXXXXX
        XX
    XXX

  XX XXX XXXXX XXXXXXX XXXXXX XXXXXXXX X XXXXXXX XXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XX X
    XXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXX XX XXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X X gettext(u'Помилка: не визначено оголошення') XX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
      XXXXXXX
    X

    XXX X
      XXXXX XXXX X XXXXX XXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXX
          XXXXXXXX XXXXXXXXXXXXXXXX XXXX
          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX XXXXXXXX
        XXX
      XXX
      XXXXX XXXX X XXXXX XXXXXXXXXXXX

      XX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XX X gettext(u'Сталася помилка') XX
        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXXXX
      X

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
    X XXXXX XXXXX X
      XXXXXXXXXXXXXXXXXXXX X X gettext(u'Помилка мережі') XX
      XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X
  XXX
XXX
XXXXXXXXX


XXXXXXXX
XXXXXXXXX XX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXX X XXX XXXXXXFFFFFFFFXXX
    XXX XXXXXXXXXXXXX X XXXXX

    XXXXXXXX XXXXXXXXXXXXXXX X
        XXX XXXXXXXXXXX X XXXXX
        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXX X X XX X X XXXXXXXXXXXXXXX XXXX X
                XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XX XXX XXXXX X XXXXX X
                    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                    XXXXXX
                X
            X
        X
        XXXXXX XXXXXXXXXXXX
    X

    XXXXX XXXXXXXX XXXXXXXXXXXXXXXX X
        XXX X
            XXXXX XXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXX XXXXXXX
                XXXXXXXX X
                    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XX
            XXX

            XXXXX XXXX X XXXXX XXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXX XX X gettext(u'Помилка генерації коду') XXX
                XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
            XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXX
        X XXXXX XXXXXXX X
            XXXXXXX gettext(u'Помилка мережі') XXX
            XXXXXXXXXXXXXXXXXXXXX
        X
    X

    XX XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    X
XXXXX
XXXXXXXXX

BBBBBBBB