BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB

XXXXXXX gettext(u'профіль користувача') XXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX

XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                    XXXX XXXXXX XXXXXXXXXXXXXXX
                BBBB
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXXX gettext(u'на платформі з')   X XXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'email веріфікован') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений користувач') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений студент') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX gettext(u'перевірений роботодавець') XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX gettext(u'поділитися профілем') XXXX
                XX XXXXXXXXXXXXXX gettext(u'написати') XXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXX
            XXXX gettext(u"Прив'язка Telegram") XXXXX

            XXX
                 gettext(u'скопіюйте цей код і відправте його боту в Telegram') 
            XXXX
            XXXX XXXXXXXXXXXXXXXX
                
            XXXXXX

            XX XXXXXXXXXXXXXXXX
                 gettext(u'код діє до')  FFFFFFFFFF
            XXXX

            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'відкрити Telegram-бота') 

            XXXX
        XXXXXX
    XXXXXX


XXXXXX

XXXX XXXXXXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXX gettext(u'всі оголошення') XXXXX

  BB BBBBBBBBB
    XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX gettext(u'всі оголошення') XXXXX XXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB B B
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXXXXXXXXBBBBBX XXXXXXXXXXX
          BBB BBBB BB BBBBBBBBB
            XXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBB BBBBBBBBBBBBBBBB
                  XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBB
                  XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBBB

              XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBXXXXXX

              BB BBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXX gettext(u'зібрано з Telegram') XXXX
                XXXXXX
              BBBBB

                BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                
                BB BBBBBBBBBBBBBBBBBBBB
                  XXX XXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    BBBB
                      FFFFFFFFFFFFFFFFFF
                    BBBBB
                  XXXXX
                BBBB
                  XXXX XXXXXXXXXXXXXX
                    BB BBBBBBBBBB
                       X
                    BBBB BBBBBBBBBBB
                       X
                    BBBB BBBBBBBBBBBBBBBB
                      BB BBBBBBBBBBBBBB X BBBBB X
                    BBBB
                      
                    BBBBB
                  XXXXXX
                
                  XXX XXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    BBBB
                      FFFFFFFFFFFFFFFFFF
                    BBBBB
                  XXXXX
                BBBBB

              XXXX XXXXXXXXXXXXX
                FFFFFFFFFFF FFFF
              XXXXXX

            XXXXXX
          BBBBBB
        XXXXXX

        BB BBBBBBBBBBBBBBBB B B
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXX XXX XXX XX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXX XXXXX XXX XXX XX
                    XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXXXXX
        BBBBB
      XXXXXX
    XXXXXXXXXX
  BBBB
    XXXX XXXXXXXXXXXXXXXXXX gettext(u'У користувача немає оголошень') XXXXXX
  BBBBB
XXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX  X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XX XXXXX XX XXXXXX XXXXXXX

    XXXXXXXX XXXXXXX
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXX X XXXXXXXXXXXXXXXX X XX X XXXX
    X

    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXXXXXXXXXXX
XXX
XXXXXXXXX
XXXXXXXX
XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX XX X
    XXXXXXXXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXX XX XXX XXXX XXXXXX

    XXX X
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX gettext(u'Ссылка скопирована!') XXX
    X XXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    X
XXX
XXXXXXXXX
BBBBBBBB