BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX gettext(u'верифікація студента') XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'верифікація студента') XXXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'введіть свою студентську електронну пошту, щоб підтвердити статус студента.') 
        XXXX

        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBB
            XXXXXX

            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                XXXXXX
            BBBBB

            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'відправити лист') 
            XXXXXXXXX
        XXXXXXX
    XXXXXX
XXXXXXXXXX
BBBBBBBB