BBBBBBB BBBBBBBBBBBBBBBBB

BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXX gettext(u'дякуємо за ваш час!') XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX XXX XXXXXXXXXX
      XXXXXX
    XXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'заявку надіслано') XXXXX
    XX XXXXXXXXXXXXXXXXXXXXX
       gettext(u"дякую! Ми отримали вашу заявку і незабаром зв'яжемося з вами.") 
    XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      
    XXXXXX

    XXXXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXX
        gettext(u'на головну') 
      XXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB