BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBB

XXXXXXXXXXXXXXX X  X XXXXXX XX XXXXX XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX

XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX

    XXXXXXXXXXX XXXXXXXX X  XXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX

    XXXXX XXXXXXXXX XXXXXXXX XX XXXXXX XXXXXX XXXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XXXXX XX XXXXX XXX XXXXXX XXXXXXX XXX XXX XXXXXXXX X XXXXXXXXXX

    XXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXX XX XXXXX X XXXXXX XXXXXXX X XXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXX X XXXXXXXXXXXX

    XXXXX XXXXXXXX XXXXXXXXXXXXXX

    XXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
        XXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXX

    XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXX XX XXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXX X X XXX XXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXX




XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXXXXXXXXBBBBBXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                        XXXXXX
                      XXXXXX
                    BBBBB

                    BB BBBBBBBBBBBBBBBB
                      XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBB
                      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBBB
                  XXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXX X X XXXXXXXXXXX
                  XXXXXX

                  XXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBXX
                    
                  XXXXX

                  XXX XXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBXX
                    BB BBBBBBBBB BBB BBBBBBBBBBBBBBB X BBBBB
                  XXXXX

                XXXXXX
              XXXX
            BBBBBB
          XXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
      BBBBB
XXXXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
BBBBBBBB