BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBB

XXXXXXXXXXXXXXX X  X XXXXXX XX XXXXX XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX


XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXX X XXXXX

    XXXXXXXXXXX XX XXXXXX XXX XXXXXXX XXXX X XXXXXX

    XXX
        XX XXXXXXXXX XXXXXXXX XX XXXXXX XXXXXX XXXXXX XXXXXXXXXX XXX XXXXXX XX XXXXXXX XXXXX X X
        XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX X XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXX
        XXXXX XXXXXXXX XXXXXX XXX XXXXX XXXXXXXXXXX XXXXXXXXX XX XXXXXX XXXXXXX
    XXXX

    XXX
        XXXXXX XXXXXXXXX XXXXX XXXXXXXX XX XXXXXXXXX XXXX XXX XXXXXXXXXXXXX
        XX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX
    XXXX

    XXXXX XXXXXXXX XXXXXXXXXXXXXX

    XXXX
        XXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
        XXXXXXXXX XX XXXXXX XXX XXXXXXXXXX
        XXXXXXXX XX XXXXXXXXXXXX
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXX XX XXXX XXXXXXXXXX
    XXXXX

    XXX
        XX XXXXXXXX XXXXX XXXXXX XX XXXXX XXX X XXXXXXX XXXX XX XXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXX XXXXXX X X
    XXXX

    XXX
        XXXX XX XXXXXX XXXXXX XXX XXXXXXX XXXX X X XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXX XXXXXXXXXX XX XXXXXXXXX XXXXXXX XXXXXXX XXXXXX
    XXXX

XXXXXXXXXX

XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BXXXXXXXXXXXXXXXXXXXXXXXBBBBBXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBB BBBBBBBXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXX X XXXXXXXXXXXXXXX
                        XXXXXX
                      XXXXXX
                    BBBBB

                    BB BBBBBBBBBBBBBBBB
                      XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBB BBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBB
                      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    BBBBB
                  XXXXXX

                  XXXX XXXXXXXXXXXXXXXXXXX
                    BB BBB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBB
                      XXX XXXXXXXXXXXXXX XXXXXX
                    BBBBB
                  XXXXXX

                  XXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBXX
                    
                  XXXXX

                  XXX XXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBXX
                    BB BBBBBBBBB BBB BBBBBBBBBBBBBBB X BBBBB
                  XXXXX

                XXXXXX
              XXXX
            BBBBBB
          XXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
      BBBBB
XXXXXXXXXX
XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX
BBBBBBBB