BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBB

XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXX
     gettext(u'робота') 
    BB BBBBBBBBB BB BBBBBBBBB X  gettext(u'шукаю роботу') BBBBB
    BB BBBBBBBBB BB BBBBBBBBB X  gettext(u'шукаю працівника') BBBBB
    BB BBBBBBBBB BB BBBBBBBBBB X  gettext(u'підробіток') BBBBB
XXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXBB BBBBBBBBB BB BBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBB BBBBBXX
         gettext(u'всі оголошення') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBB BBBBBBBBBXX
         gettext(u'шукаю роботу') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBB BBBBBBBBBXX
         gettext(u'шукаю працівника') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBB BBBBBBBBBBXX
         gettext(u'підробіток') 
    XXXX
XXXXXX

XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'всі міста') XXXXXXXXX
            BBB B BB BBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXXXXXX gettext(u'Пошук вакансії') X
               XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Зарплата від') X
                   XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Зарплата до') X
                   XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXX BB BBB BBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                     gettext(u'всі джерела') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'будь-яка зайнятість') XXXXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBBBBBBBBBBB
                XXXXXXX XXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'будь-який період') XXXXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBBBBBBBBB
                XXXXXXX XXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'застосувати') 
    XXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBB BBBBBX XXXXXXXXXX XXXXXXXXXXX
         gettext(u'скинути') 
    XXXX
XXXXXXX

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'сортування') XXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
                 gettext(u'дате ↑') 
            XXXX
        BBBB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
                 gettext(u'дате ↓') 
            XXXX
        BBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBXX
                 gettext(u'дате') 
            XXXX
        BBBBB
        X

        BB BBBBBBBBBBBB BB BBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
                 gettext(u'зарплата ↑') 
            XXXX
        BBBB BBBBBBBBBBBB BB BBBBBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
                 gettext(u'зарплата ↓') 
            XXXX
        BBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBXX
                 gettext(u'зарплата') 
            XXXX
        BBBBB
    XXXXXX

    XX XXXXXXBB BBBBBBBBB BB BBBBB
                BBB BBBBBBBBBBBBB BBBBBBBBB
             BBBB
                BBB BBBBBBBBBBBBB BBBBBBBBB
             BBBBBX
       XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'додати оголошення') XXXXXXX
    XXXX
    XX XXXXXXXXXXXXXX gettext(u'знайдено')    gettext(u'оголошень') XXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    BBB B BB BBBB
      BB BBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX
                XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXXXXXXXX
              X
                XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                   gettext(u'Активно') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                   gettext(u'Закрыто') 
                XXXXXXXXX
              XXXXXXXXX
            XXXXXX
          BBBBB

          XX XXXXXXXXXXXXXXXXX
             XXXXXXBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB BBBBXX

            XXXX XXXXXXXXXXXXX
                 BB BBB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB
                   XXXXXXXXXXXXXXXXX
                 BBBBBX

              XXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX gettext(u'Додати в обране') XX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBB BB BBBBB
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                  XXXXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'зібрано з Telegram') XXXXXXX
                    XXXXXX
                  XXXXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'зібрано з Facebook') XXXXXXX
                    XXXXXX
                  XXXXXX
                BBBBB

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'верифікований') XXXXXXX
                    XXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBB BB BBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'студент') XXXXXXX
                    XXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBB BB BBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'роботодавець') XXXXXXX
                    XXXXXX
                  BBBBB
                    BB BBBBBBBBBBBBBBBBB BB BBBBB
                        XXXX XXXXXXXXXXXX XXXXXXXXXXX
                          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXX gettext(u'нове') XXXXXXX
                        XXXXXX
                    BBBBB
                XXXXXX

                BB BBBBBBBBBBBBB
                  XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBB BBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBB
                  XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                BBBBB
              XXXXXX

              BB BBBBBBBBBBBBB BB BBBB
                XXX XXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXX XXXXXXX
                  BB BBBBBBB BB BBBBB BBBBBBBB
                     gettext(u'текста нажаль немає(') 
                  BBBB
                    
                  BBBBB
                XXXXX
              BBBB
                XXX XXXXXXXXXXXX XX
                  BB BBBBBBB BB BBBBB BBBBBBBB
                     gettext(u'текста нажаль немає(') 
                  BBBB
                    
                  BBBBB
                XXXXX
              BBBBB

              XXX XXXXXXXXXXX XX
                BB BBBBBBBBBBBBBBBBB X BBBBB X 
              XXXXX
            XXXXXX
          XXXX
        XXXXXX
      BBBBB
    BBBBBB
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBB B B
XXXX XXXXXXXXXXXXXXXXXXX

    BBB BBB BB BBBBBBBBBBBB
        BB BBB BB BBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBXXXXXX
        BBBBB
    BBBBBB
    XXX

XXXXXX
BBBBB

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

  XXXXX XXXXXX X XXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXX XXXXXXX
    XXXXXXXX X
      XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXX
    XX
  XX
  XXXXXXXXXXX XXX XX X
    XXXXX XXXX X XXXXX XXXXXXXXXXX
    XX XXXXXXXXX X
      XXXXX XXX XXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX
    X
    XXXXXX XXXXX
  XX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXX XXXXXX
  XX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX
  XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXX X
  XXX XXXXXXXXXXX X XXXXX
  XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX XXXXXX XX XXXXXXXX X
      XXXXXX X XXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
        XXXXXX
      X
    X
  X
  XXXXXX XXXXXXXXXXXX
X
XXXXXXXXX

BBBBBBBB