BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBB

XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXX
    BB BBBBBBBBB BB BBBBB
         gettext(u'Сусіди в Словаччині - оголошення') 
    BBBB BBBBBBBBB BB BBBBBBBBBBBBBB
         gettext(u'Шукаю сусіда в Словаччині') 
    BBBB BBBBBBBBB BB BBBBBB
         gettext(u'Оренда житла в Словаччині - шукаю квартиру') 
    BBBB
         gettext(u'Сусіди в Словаччині') 
    BBBBB
XXXXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXBB BBBBBBBBB BB BBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBBBBB BBBBBXX
         gettext(u'всі оголошення') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBBBBBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBXX
         gettext(u'шукаю сусіда') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBXX
         gettext(u'шукаю квартиру') 
    XXXX
XXXXXX
XXXX XXXXX XXXXXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXXX XXXX XXX
XXX XXXXXXXXXXXXXX
    BB BBBBBBBBB BB BBBBB
         gettext(u'Сусіди в Словаччині') 
    BBBB BBBBBBBBB BB BBBBBBBBBBBBBB
         gettext(u'Пошук сусіда в Словаччині') 
    BBBB BBBBBBBBB BB BBBBBB
         gettext(u'Оренда житла в Словаччині') 
    BBBB
         gettext(u'Сусіди в Словаччині') 
    BBBBB
XXXXX
XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Відкрити фільтри') 
XXXXXXXXX
XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'Всі міста') XXXXXXXXX
            BBB B BB BBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXXXXXX gettext(u'Пошук') X
               XXXXXXXXX

        XXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXXXXXX gettext(u'кількість кімнат') X
               XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Бюджет від') X
                   XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Бюджет до') X
                   XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXX BB BBB BBBBBBXXXXXXXXBBBBBX
                    XXX XXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXX BB BBBBBB BB BBBBBBBXXXXXXXXBBBBBX
                    XXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXX
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXXXXX
                XXXXXXXXX
            XXXXXXXXX
        XXXXXX
        XXXX
        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXX
        XXX
    XXXXXX
XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXXXXXX gettext(u'К-сть сусідів') X
               XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Вік від') X
                   XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'Вік до') X
                   XXXXXXXXX
        XXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'будь-який період') XXXXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'будь-яке житло') XXXXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBBBBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBB
                XXXXXXX XXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
    XXXXXX
XXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'застосувати') 
    XXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBX XXXXXXXXXX XXXXXXXXXXX
         gettext(u'скинути') 
    XXXX
XXXXXXX

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Сортировка') XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX

    
    BB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Дате ↑') 
        XXXX
    BBBB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Дате ↓') 
        XXXX
    BBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBXX
             gettext(u'Дате') 
        XXXX
    BBBBB
    X

    
    BB BBBBBBBBBBBB BB BBBBBBBB BBB BBBBBBBBBBBBB BB BBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'бюджет ↑') 
        XXXX
    BBBB BBBBBBBBBBBB BB BBBBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'бюджет ↓') 
        XXXX
    BBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBXX
             gettext(u'бюджет') 
        XXXX
    BBBBB

  XXXXXX
    XX XXXXXXBB BBBBBBBBB BB BBBBB
                BBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
             BBBB
                BBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
             BBBBBX
       XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX  gettext(u'додати оголошення') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Без реєстрації та входу') XXXXXXX
    XXXX
    XX XXXXXXXXXXXXXX gettext(u'знайдено')    gettext(u'оголошень') XXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    BBB B BB BBBB
    BB BBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                             gettext(u'Активно') 
                        XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                             gettext(u'Закрыто') 
                        XXXXXXXXX
                    XXXXXXXXX
                XXXXXX
            BBBBB

            XX XXXXXXXXXXXXXXXXX
               XXXXXXBBB BBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBB BBBBXX

                XXXX XXXXXXXXXXXXXX

                    XXXXXXX
                      XXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXX gettext(u'Додати в обране') XX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBB BB BBBBB
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXX
                            XXXXXX
                        BBBBB

                        BB BBBBBBBB
                          XXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXX
                              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXX XXXXXXXXXXXXXX gettext(u'Зібрано з ')  XXXXXXX
                            XXXXXX
                          XXXXXX
                        BBBBB


                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX gettext(u'верифікований') XXXXXXX
                                XXXXXX
                            BBBBB

                            BB BBBBBBBBBBBBBBB BB BBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX gettext(u'студент') XXXXXXX
                                XXXXXX
                            BBBBB

                            BB BBBBBBBBBBBBBBB BB BBBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX gettext(u'роботодавець') XXXXXXX
                                XXXXXX
                            BBBBB
                            BB BBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXX gettext(u'кімнат')  FFFFFFFFFFFFFXXXXXXX
                                XXXXXX
                            BBBBB
                            BB BBBBBBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXX gettext(u'депозит')  XXXXXXX
                                XXXXXX
                            BBBBB

                            BB BBBBBBBBBBBBBB BB BBBBB
                              XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXXXXXXXXX
                              XXXXXX
                            BBBBB

                            BB BBBBBBBBBBBBBBBBB BB BBBBB
                                XXXX XXXXXXXXXXXX XXXXXXXXXXX
                                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXX gettext(u'нове') XXXXXXX
                                XXXXXX
                            BBBBB

                        XXXXXX

                        BB BBBBBBBB BB BBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBB BB BBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBB
                            XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        BBBBB
                    XXXXXX

                    BB BBBBBBBB BB BBBB
                        XXX XXXXXXXXXXXXXX XXXXXX
                        XXX XXXXXXXXXXXX XXXXXXX
                          BB BBBBBBB BB BBBBB BBBBBBBB
                             gettext(u'текста нажаль немає(') 
                          BBBB
                            BB BBBBBBBBBBBBB BB BBBB
                              FFFFFFFFFFFFFFF
                            BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                              FFFFFFFFFFFFFFF
                            BBBB
                              
                            BBBBB
                          BBBBB
                        XXXXX
                    BBBB
                        XXX XXXXXXXXXXXX XX
                            BB BBBBBBB BB BBBBB BBBBBBBB
                               gettext(u'текста нажаль немає(') 
                            BBBB
                              BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                                FFFFFFFFFFFFFFF
                              BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                                FFFFFFFFFFFFFFF
                              BBBB
                                
                              BBBBB
                            BBBBB
                        XXXXX
                    BBBBB

                    XXX XXXXXXXXXXX XX
                       X FFFFFFF F F FF FFFF
                      XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFX XXXXXXXXXXXXXXXX
                    XXXXX
                XXXXXX
            XXXX
        XXXXXX
    BBBBB
    BBBBB
    BBBBBB
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBB B B
XXXX XXXXXXXXXXXXXXXXXXX

    BBB BBB BB BBBBBBBBBBBB
        BB BBB BB BBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBXXXXXX
        BBBBB
    BBBBBB
    XXX

XXXXXX
BBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

  XXXXX XXXXXX X XXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXX

  XX XXXXXXXXX XXXX XXXXXXXX XXXXXXXXXX XX XXXXXX XXXXXXX
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
  XX

  XXXXXXXXXX X
    XXXXXXX XXXXXXX
    XXXXXXXX X
      XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXX
    XX
  XX
  XXXXXXXXXXX XXX XX X
    XXXXX XXXX X XXXXX XXXXXXXXXXX
    XX XXXXXXXXX X
      XXXXX XXX XXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX
    X
    XXXXXX XXXXX
  XX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XX XXXXXXXXX XXXXXXXX XXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXX XXX XXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XX
  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX
  XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXX X
  XXX XXXXXXXXXXX X XXXXX
  XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXX XXXXXX XX XXXXXXXX X
      XXXXXX X XXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX X
        XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
        XXXXXX
      X
    X
  X
  XXXXXX XXXXXXXXXXXX
X
XXXXXXXXX
    XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXXXX X X gettext(u'Відкрити фільтри') XX
    XXXXX XXXXXXXXX X X gettext(u'Сховати фільтри') XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX X XXXXXXXXX
    XXX
XXX
XXXXXXXXX
XXXXXXXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXX X
  XXXXX XXXXX X X X XXX
  XXXXX XXXXXX X X X XXXX
  XX XXXXXXX X XX XX XXXXXX X XXX XXXXXX XXXXX
  XX XXXXXX XXX XX XXXXXX XXXX
  XX XXXXXX X X XX XXXXX X XX XXXXXX XXXX
  XXXXXX XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXXX X XX XXXXXX XXXXXXXX

  XX XXXXXXXX X XXX X
    XXXXX X X XXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
  X

  XX XXXXXXXX X XXXXX X
    XXXXX X X XXXXXXXXXXXXXXXXXX X XXXX
    XXXXX X X XXXXXXXXXXXXXXXXXX X XXXX
    XXX XXX X XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XX XX X XX XXX XX X XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXXXX XXX X X XXXXXX
  X

  XXXXX X X XXXXXXXXXXXXXXXXXX X XXXXXX
  XXXXX X X XXXXXXXXXXXXXXXXXXX X XXXXX X XXXX
  XXX XXX X XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX
  XX XX X XX XXX XX X XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
  XXXXXX XXX X X XXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXX XXXXX X XXXXXXX X XXX
  XXXXX XXXX X XXXXX X XXX

  XX XXXXXX X XX  XXXXXX XXXXXXXXXX
  XX XXXXXX X XX  XXXXXX XXXXXXXXXX
  XX XXXXXX X XXX XXXXXX XXXXXXXXXX
  XX XXXXX X XX   XXXXXX XXXXXXXXXX
  XX XXXXX X XX   XXXXXX XXXXXXXXXX
  XX XXXXX X XXX  XXXXXX XXXXXXXXXX
  XXXXXX XXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
      XXXXXXXXX X XXXXX XXXXXXXXXX
      XXXXXXX
    X

    XXXXX XXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXX
BBBBBBBB