BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXX
XXXXXXX
  FFFFFFFFFFFFFFFFBB BBBBBBBBB  gettext(u'за')  XBBBBBBB BBBBBBBBBBBBBBBBBBBB X BBBBB X XXXXXXXX
XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXBB BBBBBBBBB  gettext(u'за')  XBBBBBBB BBBBBBBBBBBBBBBBBBBB  gettext(u'в')  BBBBBX  gettext(u'Оголошення на pusto.sk — речі, робота, житло та сусіди в Словаччині.') XX
XXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BXXXXXXXXXBBBBBX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBB BBBBB BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXXXBBBBBXX
              XXXX
                XXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                XXXXXX
                XXXXXBB BBBBBBBBBBBBBBBBBBBB X BBBBBBB BBBBBBBBBX XBBBBBX
                XXXXXXXXXBB BBBBBBBBBBBBBXXXXXBBBBXXXXBBBBBX
                XXXXXXXXXXXXXXXX
              X
            XXXXXX
          BBBBBB
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXFFFFFF
        XXXXXX
      XXXXXX

      BB BBB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBB B B
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          BBB BBBBB BB BBBBBBBBBBBBB
            XXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXXXBBBBBX
              XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBXXXXBBBBXXXXXBBBBBX
              XXXXXXXXXXXX gettext(u'Фото')  X
            X
              XXXX
                XXXXXX
                XXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX
              X
            XXXXXXXXX
          BBBBBB
        XXXXXX
      BBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XX
        XXXXBB BBB BBBBBBBBBBBBBBBBBBB XXX
        XXXX  XXX XXXXXXXXXXXXXX XXX
        XXXX    BB BBBBBBBBB XXX
        XXXX      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX    BBBB BBBBBBBBBBBBBBB XXX
        XXXX      XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX
        XXXX    BBBB BBBBBBBBBB XXX
        XXXX      XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXX    BBBBB XXX
        XXXX  XXXXX XXX
        XXXXBBBBB XXX

        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

        XXX XXXXXXXXXXXX X
            XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBFFFFFFFFFFFFFFFFFBBBBBBBBBXX

          BB BBBBBBBBB BB BBBBB BBBBBBBB
             gettext(u'текста нажаль немає(') 
          BBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              FFFFFFFFFFFFFFFFF
            BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              FFFFFFFFFFFFFFFFF
            BBBB
              
            BBBBB
          BBBBB

        XXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX

              BB BBBBBBBBBB
                  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBB
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXX gettext(u'Зібрано з')  XXXXXXX
              BBBBB

              BB BBBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBBBBBBBBBB BB BBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFF  gettext(u'кімнат') XXXXXXX
              BBBBB

              BB BBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
              BBBBB

              BB BBBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX FFFFFFFFFFFFXXXXXXX
              BBBBB

              BB BBBBBBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBBB

              BB BBBBBBBBBBBB BB BBBBBBBBBBBBBB

                  BB BBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX  gettext(u'сусідів') XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX
                           gettext(u'Я') 
                          BB BBBBBBBBBBBBB BB B
                               gettext(u'чоловічої') 
                          BBBB BBBBBBBBBBBBB BB B
                               gettext(u'жіночої') 
                          BBBBB
                           gettext(u'статі') 
                      XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX
                           gettext(u'Шукаю сусіда') 
                          BB BBBBBBBBBBBBBBBBBBB BB B
                               gettext(u'чоловічої статі') 
                          BBBB BBBBBBBBBBBBBBBBBBB BB B
                               gettext(u'жіночої статі') 
                          BBBB BBBBBBBBBBBBBBBBBBB BB B
                               gettext(u'будь-якої статі') 
                          BBBBB
                      XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX
                           gettext(u'шукаю') 
                          BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                              
                          BBBB
                              
                          BBBBB
                      XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX
                           gettext(u'бажаний вік сусіда(ів) від') 
                          
                           gettext(u'до') 
                          
                      XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX
                           gettext(u'на')  
                      XXXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBB
                      XXXXX XXXXXXXXXXXXXX gettext(u'перевірено адміном') XXXXXXX
                  BBBBB

              BBBBB

              BB BBBBBBBB
                  XXXXX XXXXXXXXXXXXXXXXXXXXX
              BBBBB

          XXXXXX
      XXXXXX

      BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          BB BBBBBBBB BB BBBBB BBBBBBBB
             gettext(u'опису немає') 
          BBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              FFFFFFFFFFFFFFFF
            BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              FFFFFFFFFFFFFFFF
            BBBB
              
            BBBBB
          BBBBB
        XXXXXX


        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX gettext(u'Показать всё') XXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBB
              XX XXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX
                 XXXXXXXXXXXXXX
                 gettext(u'перейти в джерело') 
              XXXX

              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX
                 XXXXXXXXXXXXXX
                 gettext(u'Я вже в групі — перейти до оголошення') 
              XXXX
            BBBB BBBBBBBBBBBBBB
             XX XXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX
                 XXXXXXXXXXXXXX
                 gettext(u'перейти в джерело') 
              XXXX

            BBBB BBBBBBBBBBBBBBBBB
              XX XXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXX XXXXXXXXXXX
                 XXXXXXXXXXXXXX
                 gettext(u'перейти в джерело') 
              XXXX
            BBBBB
          XXXXXX
        BBBB
          XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX gettext(u'написати') XXXXXXXXX

          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXX gettext(u'Зв’язатися з автором') XXXXX

              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBXX
                BBBBBBBBBB

                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX
                  XXXXXX
                BBBB
                  XXXX XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                  XXXXXX
                BBBBB

                XXXX XXXXXXXXXXXXXX
                  XXXXXXX gettext(u'Повідомлення') XXXXXXXX
                  XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXXXXX XXXXXXXXXXXXXX gettext(u'Відправити') XXXXXXXXX
              XXXXXXX
            XXXXXX
          XXXXXX
        BBBBB

        XXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXBBBBBX
          BB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXBBBBB
          XXXXXXXXXXXXXXXXXXXBB BBBBBBB BB BBBBBBBBXXXXXXXXXXBBBB BBBBBBB BB BBBBBBBBBBBXXXXXXXXXXXXBBBB BBBBBBB BB BBBBBBXXXXXXXBBBBBX
          XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXBB BBBBBBBBBBBB gettext(u'Видалити з обраного') BBBB gettext(u'Додати в обране') BBBBBX
          XXXXXXXXXXXXXXBB BBBBBBBBBBBBXXXXBBBBXXXXXBBBBBXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBXBBBBXBBBBBXXXXXXX
        XXXXXXXXX
      XXXXXX

      BB BBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX
          XXXX XXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB
              XXXX XXXXXX XXXXXXXXXXXXXXX
            BBBB
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'на платформі з')  FFFFFFFFFFFFXXXXXXX
            XXXXXX
          XXXXXX
        XXXX
      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBB
          XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXX gettext(u'це моє оголошення?') XXXXXXXXXXX
        BBBBB
        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBXX
          XXXXXX gettext(u'скожі оголошення') XXXXXXX
        XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBXX
          XXXXXX gettext(u'поскаржитись на оголошення') XXXXXXX
        XXXX
      XXXXXX
    XXXXXX

  XXXXXX
XXXXXX

XXXXXXXX
  XXXXX XXXXXXXXXXXXXXX X XFFFFFFFFXX

  XXXXX XXXXXXXXXXXXXXXXX X X
    XXXXXXXX XFFFFFFFFXX
    XXXXXXXX XFFFFFFFFXX
    XXXXXX XFFFFFFFFFFFFFFFFFFXX
    XXXXX XFFFFFFFFFFFFFFFFFFXX
    XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBXXXXBBBBXXXXXBBBBB
  XX

  XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X XXX X
    XX XXXXXXX XXXX XXX XXXXXXXXXXX XXXXXXX

    XXXXXXXXXXXXX XXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX
    XXX
  X
XXXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
  XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXX
    XX
    XXXXXX XXXXX X XXXXXXXX X XXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXX
    XXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXX X XXXX X
    XXXXX X X XXX XXXXXXX
    XXXXXXXXXXXXXXXXXXXXX X XXXX X XX X XX X XX X XXXXXX
    XXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XXXXXX X
        XXXX XXXXXXXX
        XXXX XXXXXXX
        XXXX XXXXXXX
        XXXX XXXXXXXXX
        XXXX XXXXXXXX
      XXXXX
    XXX
  X

  XXXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXX

    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
        XXXXXXXXXXXXXXXXXXX

        XXX XXXXXXXXX X XXXXXX

        XXXXXXXX XXXXXXXXXXXXXX X
          XX XXXXXXXXXXX XXXXXXX
          XXXXXXXXX X XXXXX
          XXXXXXXXXXXXXX
        X

        XX XXXXXXX XXXX XXX XXXXXXXXXXX X
          XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXX

          XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
        X XXXX X
          XXXXXXXXXXXXXXX
        X
      XXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXX XXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
      XX XXXXXXXXX XXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
    XXX
  XXXXX

  XXXXXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXXXXXXXX X
      XX XXXXXXX XXXXXXX

      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXX

      XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXX

      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXX X XXXXXXXXXX
        X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXX

      XXX XXX X XXXXXXXXX
        XX
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX
      XX

      XXX XXXXXX X XXXXX

      XXXXXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
          XXXXX XXXXXX X X XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXX X XXXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX X
          XXXXX XXXXXX X X XXX XXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXX X XXXXXXXXX
        XXX

        XX XXXXXXX X
          XXXXXXXXXXXXXXXXX X XXXX X XX X XXX X XXXXXXXXXXXXXX
        X

        XX XXXXXXXXXXX XX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXX
          XXX
        X

        XX XXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XX XX
      X

      XXXXXXXX XXXXXXXXX X
        XXX X XX X XXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        XXXXXXXXX
      X

      XXXXXXXX XXXXXX X
        XXXXXXXXXX X XXX
      X

      XXXXXXXX XXXXXX X
        XXXXXXXXXX X XXX
      X

      XX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
          XXXXXXXXXXXXXXXXXXX
          XXXXXXX
        XXX
      X

      XX XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
          XXXXXXXXXXXXXXXXXXX
          XXXXXXX
        XXX
      X

      XXXXXXXXXXXXXXXXXXXXXXX XXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX
        XXX
      XXX

      XX XXXXXXXXX XX XXXXXXXXXXXXX X XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXX XXX X
            XXXXXX X XXXXXXXXXXXXXXXXXXXXX
          XX
          X XXXXXXXX XXXX X
        XX

        XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXX XXX X
            XX XXXXXXX XXX XXXXX XXXXXXX

            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XX X XXXX X XXXXXXX
            XXXXXX X XXXXX

            XX XXXXXXXXXXXXX X XXX XXXXXXX

            XX XXX X XX XXXXXXX
            XXXX XXXXXXX
          XX
          X XXXXXXXX XXXX X
        XX
      X

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX X
        XX XXXXXX XXX XXXXXXXXXXXX XXXXXXX
        XX XXXXXX XXX XXXXXXXXXXXXX XXXXXXX
      XXX

      XXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX

  XXXXXXXXX XXXXXXXXXXXXXXXXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX XX XXXXX XX XXXXX XXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
      XXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX

      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXX X
          XXXXXX XXXXXXXXXXXXXXXX
        XX
        XXXXXXXXXXXXX XXX X
          XXXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XX
        XXXXXXXXXX
    X

    XXXXX XXX X XXXXXXXXXXXXXXXX XX XXX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
    XXXXX XXXX X XXXXXXXXXX X XX

    XX XXXXXXXXXXXXXXXXXX XX XXXX X XX X
      XXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXX X XXXXXXXXXXX X XXXXXXXXX XXXX X XXXXXXXXX
    XXX
  XXXXX

  XXXXXXXXX XXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXX X
      XXX X
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXX X
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
      X XXXXX XXX X
        XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX
      X

      XXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXX X XXXXXXXXXXXXXXXXX X XXX
      X XXXXX XXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX
        XXXXXX XXX
      X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXX X
      XXX X
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      X XXXXX XXX X
        XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX
      X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
      XX XXXXXX XX XXXXXX XXXX XXX XXXXXXXXX XXXXXX XXX

      XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXX X XXX
        X

        XXXXXXXXX X XXXXXXXXX
          XXXXXXXXXXXXX XXX X
            XXXXXX XXXXXXXXXX
          XX
          XXXXXXXXXXXXXXXX XXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXX
      XXX

      XXXXXX XXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX X XXX
      X

      XXXXX XXXX X XXXXXXXXXXXXXXXXXX
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXX

      XXX XXXXXXXX X XXXXXX

      XX XXXXXX XXX XXX X
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXX X XXXXX
      X XXXX X
        XXXXXXXXXXXXXXXXXX XXX
        XXXXXXXX X XXXXXX
      X

      XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX

      XXXXXX XXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXX X XXXXXXXXX
      XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXX X XXXXXXXXX X XXXXXXXXX X XXXXXXX X XXXXXXX
      XX

      XX XXXXXX X
        XXXXXXXXXXXXXXXX X XXXXXXXX X XXX X XXXX
      X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX
        X

        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
      XXX
    X

    XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXX X XXXXXXXXXXXXXXXX
      XX XXXXXX XXXXXX XXXXXX

      XXX X
        XXXXX XXX X XXXXX XXXXXXXXXX X
          XXXXXXX XXXXXXX
          XXXXXXXX X
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XX
        XXX

        XX XXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX
          XXXXXX XXXXX
        X

        XXXXX XXXX X XXXXX XXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXX XXX XXXXXXXX

        XXXXXXXXXXXXXXX XXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXX X XXXXXXX X XXXXXXXXX
        XXX

        XXXXXX XXXXX
      X XXXXX XXXXX X
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXX
        XXXXXX XXXXX
      X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXX
        XXXXXX XXXXXX
      X

      XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXX XXXXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX X XXXXXXX X XXXXXXXXX
      XXX

      XXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX X
      XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXX XXXXXXX

      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX

      XX XXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      X

      XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
      X

      XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXX XXXXXXXX XXX XXXXX XXXXXXX XXXXX
    XXX

    XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXX
XXXXXXXXX

BB BBBBBBB BB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXX
  XXXXXXX XFFFFFFFFXX
  XXXXXXXXXXXXXX XFFFFFFFFFFFFFFFFFFFFFFFFFXX
  BB BBBBBBBBBBBBB
  XXXXXXXX XXFFFFFFFFXXX
  BBBBB
  BB BBBBBBBBB
  XXXXXXXXX X
    XXXXXXXX XXXXXXXX
    XXXXXXXX XXX
    XXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XFFFFFFFFX
  XX
  BBBBB
  XXXXXXXX X
    XXXXXXXX XXXXXXXX
    XXXXXXX XXXXXXXXXX
  X
X
XXXXXXXXX
BBBBB


BBBBBBBB