BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXXXXXX XX XXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXXXXX XXXXXX XX XXXXX XXXXXXX X XXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBB BBBBBXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX gettext(u'речі') XXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX gettext(u'Б/У або нові') XXXXX
                XXXX gettext(u'купуй або продавай речі серед студентів') XXXXX
            XXXXXX
        XXXXXX
    XXXX
     #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

    XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX gettext(u'житло') XXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX gettext(u'сусіди та житло') XXXXX
                XXXX gettext(u'пошук житла та сусідів') XXXXX
            XXXXXX
        XXXXXX
    XXXX

XXXXXX



BBBBBBBB