BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB

XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXXXX
    BB BBBBBBBBB BB BBBBBB
         gettext(u'Продаж товарів в Словаччині - pusto.sk') 
    BBBB BBBBBBBBB BB BBBBB
         gettext(u'Купівля товарів в Словаччині - pusto.sk') 
    BBBB BBBBBBBBB BB BBBBBB
         gettext(u'Безкоштовні оголошення в Словаччині - pusto.sk') 
    BBBB
         gettext(u'Оголошення в Словаччині - pusto.sk') 
    BBBBB
XXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXX    XX XXXXXXBBB BBBBBBBBBBBBXX gettext(u'Головна') XXXX XXX
XXXX XXX
XXXX    XXXXXXXXXXXXXX XXX
XXXX XXX
XXXX    XX XXXXXXBBB BBBBBBBBBBBBBBBBXX XXX
XXXX         gettext(u'Речі')  XXX
XXXX    XXXX XXX
XXXX XXX
XXXX    BB BBBBBBBBBBB XXX
XXXX        XXXXXXXXXXXXXX XXX
XXXX        XXXXXXXXXXXXX XXX
XXXX    BBBBB XXX
XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXBB BBBBBBBBB BB BBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBB BBBBBXBBBBBBBBBBBBBBB BBBBBBBXX
         gettext(u'всі оголошення') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBB BBBBBBXBBBBBBBBBBBBBBB BBBBBBBXX
         gettext(u'продаж') 
    XXXX

    XX XXXXXXXBB BBBBBBBBB BB BBBBBXXXXXXXXXBBBBBX
       XXXXXXBBB BBBBBBBBBBBB BBBBBXBBBBBBBBBBBBBBB BBBBBBBXX
         gettext(u'купівля') 
    XXXX
XXXXXX
XXXX
    BB BBBBBBBBB BB BBBBB
         gettext(u'Оголошення в Словаччині') 
    BBBB BBBBBBBBB BB BBBBBB
         gettext(u'Оголошення про продаж товарів в Словаччині') 
    BBBB BBBBBBBBB BB BBBBB
         gettext(u'Оголошення про купівлю товарів в Словаччині') 
    BBBBB
XXXXX

XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Відкрити фільтри') 
XXXXXXXXX

XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'всі міста') XXXXXXXXX
            BBB B BB BBBBBB
                XXXXXXX XXXXXXXX BB BBBBBBBBBBB BB BXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX

        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXX
               XXXXXXXXXXXXXXX XXXXXX
               XXXXXXXXXXXXX gettext(u'пошук') X
               XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'ціна від') X
                   XXXXXXXXX

            XXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXX
                   XXXXXXXXXXXXX gettext(u'ціна до') X
                   XXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXX BB BBB BBBBBBXXXXXXXXBBBBBX
                    XXX XXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXXXXX BB BBBBBB BB BBBBBBBBBBXXXXXXXXBBBBBX
                    XXXXXXXX
                XXXXXXXXX

                XXXXXXX XXXXXXXXXXXXX BB BBBBBB BB BBBBBBBXXXXXXXXBBBBBX
                    XXXXX
                XXXXXXXXX
            XXXXXXXXX
        XXXXXX
        XXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXXXXX gettext(u'будь-який стан') XXXXXXXXX
            BBB BBBBBB BBBBB BB BBBBBBBBBB
                XXXXXXX XXXXXXXX
                    BB BBBBBBBBBBBBBBBB BB BBBBBXXXXXXXXBBBBBX
                    
                XXXXXXXXX
            BBBBBB
        XXXXXXXXX
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBX
       XXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBBXXXXXXBBBBBXX
         gettext(u'Все') 
    XXXX

    BBB BBB BB BBBBBBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBB BBBBBBX
           XXXXXXXXXXXX BB BBBBBBBBBBBBBBB BB BBBBBBBBXXXXXXBBBBB BB BBBBBBBBBBBBBBB B BBXXXXXXXXXXXXXXXBBBBBXX
            BB BBBBBBBBBBBBB BB BBBB
                
            BBBB BBBBBBBBBBBBB BB BBBB
                
            BBBB
                
            BBBBB
        XXXX
    BBBBBB

    BB BBBBBBBBBBBBBBBBB B BB
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX XXX
        XXXXXXXXX
    BBBBB

    XXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'застосувати') 
    XXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBB BBBBBX XXXXXXXXXX XXXXXXXXXXX
         gettext(u'скинути') 
    XXXX


XXXXXXX

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Сортировка') XXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX

    BB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Дате ↑') 
        XXXX
    BBBB BBBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Дате ↓') 
        XXXX
    BBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBBBBBBBBBBXX
             gettext(u'Дате') 
        XXXX
    BBBBB
    X

    BB BBBBBBBBBBBB BB BBBBBBB BBB BBBBBBBBBBBBB BB BBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Цене ↑') 
        XXXX
    BBBB BBBBBBBBBBBB BB BBBBBBB BBB BBBBBBBBBBBBB BB BBBBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXX
             gettext(u'Цене ↓') 
        XXXX
    BBBB
        XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBXX
             gettext(u'Цене') 
        XXXX
    BBBBB

  XXXXXX
    XX XXXXXXBB BBBBBBBBB BB BBBBB
                  BBB BBBBBBBBBBBBBBBB BBBBBB
               BBBB
                  BBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
               BBBBBX
         XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

        XXXXXXX  gettext(u'додати оголошення') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Без реєстрації та входу') XXXXXXX
    XXXX
    XX XXXXXXXXXXXXXX gettext(u'знайдено')    gettext(u'оголошень') XXXX
XXXXXX

XXXX XXXXXXXXXXXXX
    BBB B BB BBBB
    BB BBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBB
    BB BBBBBBBBBB BB BBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                             gettext(u'Активно') 
                        XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXX BB BBBBBBBB BB BBBBBBBBXXXXXXXXBBBBBX
                             gettext(u'Закрыто') 
                        XXXXXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX
                X
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

                    BBB BBB BB BBBBBBBBBBBBBBBB
                        XXXXXXX
                            XXXXXXXX
                            BB BBBBBBBBBBBBB BB BBBBBB
                                XXXXXXXX
                            BBBBB
                        X
                            
                        XXXXXXXXX
                    BBBBBB
                XXXXXXXXX

            XXXXXX
    BBBBB

            XX XXXXXXXXXXXXXXXXX
                XXXXXXBBB BBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBXX

          XXXX XXXXXXXXXXXXXX
            XXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX gettext(u'Додати в обране') XX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBB BB BBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                XXXXXX
              BBBBB

              BB BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX gettext(u'Зібрано з ')  XXXXXXX
                  XXXXXX
                XXXXXX
              BBBBB

              XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'верифікований') XXXXXXX
                    XXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'студент') XXXXXXX
                    XXXXXX
                  BBBBB

                  BB BBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXX
                    XXXXXX
                  BBBBB

                  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX gettext(u'роботодавець') XXXXXXX
                    XXXXXX
                  BBBBB
                  BB BBBBBBBBBBBBBBBBB BB BBBBB
                      XXXX XXXXXXXXXXXX XXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX gettext(u'нове') XXXXXXX
                      XXXXXX
                  BBBBB
              XXXXXX
              BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBB BBBBBBBBBBBBB
                XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBB BBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBB
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              BBBBB
            XXXXXX
              BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB

              BB BBBBBBB BB BBBB
                XXX XXXXXXXXXXXXXX XXXXXX

                XXX XXXXXXXXXXXX XXXXX XX
                  BB BBBBBBB BB BBBBB BBBBBBBB
                     gettext(u'текста нажаль немає(') 
                  BBBB
                    BB BBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFF
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFF
                    BBBB
                      
                    BBBBB
                  BBBBB
                XXXXX

              BBBB

                XXX XXXXXXXXXXXX  XX
                  BB BBBBBBB BB BBBBB BBBBBBBB
                     gettext(u'текста нажаль немає(') 
                  BBBB
                    BB BBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFF
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                      FFFFFFFFFFFFFFF
                    BBBB
                      
                    BBBBB
                  BBBBB
                XXXXX

              BBBBB

              XXX XXXXXXXXXXX XX
                 X FFFFFFF F F FF FFFF
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFX XXXXXXXXXXXXXXXX
              XXXXX
          XXXXXX
        XXXX
        XXXXXX
    BBBBB
    BBBBB
    BBBBBB
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBB B B
XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBB BB BBBBBBBBBBBB
        BB BBB BB BBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB
            XX XXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBXXXXXX
        BBBBB
    BBBBBB
    XXX
XXXXXX
BBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBB BXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXX X XXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX
    XX

    XXXXXXXXXX X
        XXXXXXX XXXXXXX
        XXXXXXXX X
            XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX
        XXXXX XXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXX
        XX
    XX
    XXXXXXXXXXX XXX XX X
        XXXXX XXXX X XXXXX XXXXXXXXXXX

        XX XXXXXXXXX X
            XXXXX XXX XXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX
        X

        XXXXXX XXXXX
    XX
    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXX

        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXX XXX XXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
    XXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX
    XXX
XXX

XXXXXXXX XXXXXXXXXXXXXXX X
    XXX XXXXXXXXXXX X XXXXX

    XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXX XXX X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXX XXXX XXXXXX XX XXXXXXXX X
            XXXXXX X XXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX X
                XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
                XX
                XXXXXX
            X
        X
    X

    XXXXXX XXXXXXXXXXXX
X
XXXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXX XXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXX
    XXX
XXX

XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX
    X
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX
    XX
    X
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    BB BBBBBBBBBBB
    X
    X
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXX
      XXXXXXXXX
    X
    BBBBB
  X
X
XXXXXXXXX
    XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXX

    XXXXX XXXXXXXX X X gettext(u'Відкрити фільтри') XX
    XXXXX XXXXXXXXX X X gettext(u'Сховати фільтри') XX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX X XXXXXXXXX
    XXX
XXX
XXXXXXXXX

XXXXXXXX
XXXXXXXX XXXXXXXXXXXX XXXX XXXX XXXXX X
  XXXXX XXXXX X X X XXX
  XXXXX XXXXXX X X X XXXX
  XX XXXXXXX X XX XX XXXXXX X XXX XXXXXX XXXXX
  XX XXXXXX XXX XX XXXXXX XXXX
  XX XXXXXX X X XX XXXXX X XX XXXXXX XXXX
  XXXXXX XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXXX X XX XXXXXX XXXXXXXX

  XX XXXXXXXX X XXX X
    XXXXX X X XXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
  X

  XX XXXXXXXX X XXXXX X
    XXXXX X X XXXXXXXXXXXXXXXXXX X XXXX
    XXXXX X X XXXXXXXXXXXXXXXXXX X XXXX
    XXX XXX X XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XX XX X XX XXX XX X XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXXXX XXX X X XXXXXX
  X

  XXXXX X X XXXXXXXXXXXXXXXXXX X XXXXXX
  XXXXX X X XXXXXXXXXXXXXXXXXXX X XXXXX X XXXX
  XXX XXX X XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXX
  XX XX X XX XXX XX X XXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
  XXXXXX XXX X X XXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
  XXXXX XXXXX X XXXXXXX X XXX
  XXXXX XXXX X XXXXX X XXX

  XX XXXXXX X XX  XXXXXX XXXXXXXXXX
  XX XXXXXX X XX  XXXXXX XXXXXXXXXX
  XX XXXXXX X XXX XXXXXX XXXXXXXXXX
  XX XXXXX X XX   XXXXXX XXXXXXXXXX
  XX XXXXX X XX   XXXXXX XXXXXXXXXX
  XX XXXXX X XXX  XXXXXX XXXXXXXXXX
  XXXXXX XXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
      XXXXXXXXX X XXXXX XXXXXXXXXX
      XXXXXXX
    X

    XXXXX XXXXXXX X XXXXXXXXXXX X XXXXXXXXXXXXXXXXXX X XXXXXX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX X XXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXXXX
BBBBBBBB