BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBB
XXXXXXX gettext(u'мої обрані') XXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

XXX XXXXXXXXXXXXXXXXXX gettext(u'збережені оголошення') XXXXX

XXXX XXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX gettext(u'речі') XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'завантаження…') XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXX XXX XXX XX
                XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX gettext(u'проживання') XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'заванатження…') XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX
          XXXXX XXXXX XXX XXX XX
                XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX
                XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
  XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX  XXXX XXXXXXXXXXXXXXXXXXX XXX
  XXXX    XXX XXXXXXXXXXXXXXX gettext(u'💼 робота / працівники') XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX  XXXXXX XXX
XXXX XXX
  XXXX  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'заванатження…') XXXXXX XXX
XXXX XXX
  XXXX  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXX
  XXXX    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
  XXXX      XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX XXX
  XXXX        XXXXX XXXXXX XXXX X X XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX      XXXXXX XXX
  XXXX    XXXXXXXXX XXX
XXXX XXX
  XXXX    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
XXXX XXX
  XXXX    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
  XXXX      XXXX XXXXXXXXXX X XX XXX XXXXXXXXXX XXXXXXXXXXXX XXX
  XXXX        XXXXX XXXXX XXX XXX XX XXX
  XXXX              XXXXXXXXXXXXXXXXXXXXX XXX
  XXXX              XXXXXXXXXXXXXXXX XXX
  XXXX              XXXXXXXXXXX XXX
  XXXX              XXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX              XXXXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX      XXXXXX XXX
  XXXX    XXXXXXXXX XXX
  XXXX  XXXXXX XXX
  XXXXXXXXXXXXXX XXX

XXXXXX

XXXXXXXX
XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX X XBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBBXX

XXXXXXXX XXXXXXXXXXXXXXXXXX X
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX X XXXXXXX X XXXXXXXXXXX
  XX
  XXXXXX XXXXX X XXXXXXXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
  XXXXX XXX X XXXXXXXXXXXXXXXXXXX
  XXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXX X XXXX X
  XXXXX X X XXX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXX X XXXX X XX X XX X XX X XXXXXX
  XXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
  XXX X
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX X
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  X XXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX
  X

  XXX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXX X XXXXXXXXXXXXXXXXX X XXX
  X XXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX
    XXXXXX XXX
  X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXX X
  XXX X
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
  X XXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX
  X
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXX XX XXXXXX XXXX XXX XXXXXXXXX XXXXXX XXX

  XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXX X XXX
    X

    XXXXXXXXX X XXXXXXXXX
      XXXXXXXX XX XXXXXXXXXX
      XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
  XXX

  XXXXXX XXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX X
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX X XXX
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXX

  XX XXXX XXX XXX X
    XXXXXXXXXXXXXXX XXX
  X

  XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
  XXXXXX XXXXXXXXXXXX XX XXX
    XXXXXXXXXXXXXXXX XXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXX
X

XXXXXXXX XXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XX XXXXX XX XXXXXX XXXXXXX

    XXXXXXXX XXXXXX X
      XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXX X XXXXXXXXXXXXXXXX X XX X XXXX
    X

    XXXXXXXXXXXX X XX XX X
      XXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXX
    XX

    XXXXXXXXXXXX X XX XX X
      XXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXX XXX
    XX
  XXX
X

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXXXX X
    XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
  X

  XX XXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXX
  X

  XX XXXXX XX XXXXX X
    XXXXX XXXXXXXXXX X XXXXX X XX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XX X XXXXXXX
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XX X XXXXXXX
  X

  XX XXXXXX XXX XX X
    XX XXXXXXX X
      XXXXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXX X X gettext(u'Поки нічого немає') XX
    X
    XX XXXXXXXX X
      XXXXXXXXXXXXX X XXXXX
    X
  X XXXX X
    XX XXXXXXX X
      XXXXXXXXXXXX X XXXXX
    X
    XX XXXXXXXX X
      XXXXXXXXXXXXX X XXXXXX
    X
  X
X

XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X
  XXXXX XXX X XXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
      X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
  XX

  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXX
  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXX XX XXXX
  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX

  XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXX X X
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX gettext(u'зібрано з Telegram') XXXXXXX
      XXXXXX
    XXXXXX
  X X XXX

  XXXXX XXXXXXXXXXXX X X
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'верифікований') XXXXXXX
        XXXXXXX X XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'студент') XXXXXXX
        XXXXXXX X XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX gettext(u'роботодавець') XXXXXXX
        XXXXXXX X XXX
    XXXXXX
  XX

  XXX XXXXX X XXX
  XX XXXXXX XXX XXXXXXXXXXXX XX XXXXXXXXXXX X
    XXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  X XXXX XX XXXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXXXXX X
    XXXXX X XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  X XXXX XX XXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXXXX X
    XXXXX X XXXX XXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X X X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX X
    XXXXXXX
  X

  XXXXXX X
    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX gettext(u'Видалити з обраного') XX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX
          XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX X XXXXX X XXX
        XXXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX X X XXXXX X XXXXX
          XXXXXXXX
        XXXXX

        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX X X XXXXX X XXXXX
          XXXXXXXXXXXXX XX XXXXXXXXX X X X X X XXXXXXXXXXXXXXX
        XXXXX
      XXXXXX
    XXXX
  XX
X

XXXXXXXX XXXXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXX X XXX

    XX XXXXXXX X
      XXXXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXX X X gettext(u'Завантаження…') XX
    X

    XX XXXXXXXX X
      XXXXXXXXXXXXX X XXXXX
    X
  XXX
X

XXXXXXXX XXXXXXXXXXXXXXX X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXX XXXXXXXXXXXXXXX X XXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXX

    XX XXXXXXX X
      XXXXXXXXXXXX X XXXXXX
      XXXXXXXXXXXXXXXXX X X gettext(u'Не вдалося завантажити обране') XX
    X

    XX XXXXXXXX X
      XXXXXXXXXXXXX X XXXXX
    X
  XXX
X

XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXX

  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXX X X
  XX

  XX XXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXX XXXXXXXXXXXXXXX X XXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXX
    XXXXXXX
  X

  XXX XXXX
  XXX X
    XXX X XXXXX XXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXX X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XX
      XXXXX XXXXXXXXXXXXXXXX XXXXX XX
    XXX
  X XXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXX
    XXXXXXXXXXXXXXXX
    XXXXXXX
  X

  XX XXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXX
  X

  XXX XXXXX
  XXX X
    XXXX X XXXXX XXXXXXXXXXX
  X XXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX
    XXXXXXXXXXXXXXXX
    XXXXXXX
  X

  XX XXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXXX
  X

  XXXXX XXXX X XXXXXXXXX XX XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXX

    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X XXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXX

  XXXXXXXXXXXXXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXX XXXXXXX

  XXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXX

  XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXX
    XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

  XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXX X XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX

  XX XXXXXXX XXXXXXX

  XXXXXXXXXXXXXXXXXX X XXXX
  XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX X XXXX XXXX XXXXXX

  XXXXXXXXXXXXX XX X
    XXXXXXXXXXXXXX

    XX XXXXXXXXX XX XXXXXXX XXXXXXX

    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XX XXXXX
XXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
  XXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXX
XXX
XXXXXXXXX

BBBBBBBB