BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX

XXXX XXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX
            BB BBBB BB BBBBBBBB
                 gettext(u'купівля банера') 
            BBBB BBBB BB BBBBBB
                 gettext(u'купівля рекламного посту') 
            BBBBB
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'днів за')   XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'розміщення у стрічці оголошень') 
        XXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB

        

        XXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXX
            
            
        XXXXXX

        XXXX XXXX XXX
        XXXX XXXXXXXXXXXXXX
            
            
        XXXXXX

        XXXX XXXXX XXXXXX XXX
        BB BBBB BB BBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            

            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'завантажте банер') XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X  gettext(u'до 1MB') XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'файл не обран') XXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'вибрати') XXXXXXX
                XXXXXX
              XXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Приклад у стрічці') XXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX

        BBBB BBBB BB BBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            

            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

              XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Завантажте зображення посту') XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X  gettext(u'до 1MB') XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'файл не обран') XXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'вибрати') XXXXXXX
                XXXXXX
              XXXXXXXX

              
              XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'приклад') XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                         XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'приклад') XXXX

                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'приклад') XXXX
                    XXXXXX

              XXXXXX
            XXXXXX
          XXXXXX
        BBBBB

        XXXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Надіслати заявку') 
        XXXXXXXXX

    XXXXXXX
XXXXXX

XXXXXXXX
    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXX XXXX X XXXXXXXXXXX XX XXXXXXXXXXXXXXX
        XX XXXXXXX XXXXXXX

        XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXX XXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        X
    XXX
XXXXXXXXX

XXXXXXXX
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX X X gettext(u'Заголовок объявления') XX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXX XX X XXXXX X XXXXXXXXXXXX
    X

    XX XXX XXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XX XXX XXXXXXXX XXXXXXXX XXXXX XXXX XXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
BBBBBBBB