BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBB
XXXX gettext(u'оплата реклами') XXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'оплатити') XXXXXXXXX
XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXX
  XXXXX XXXXXXXXXXXX X XXX

  XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXX X XXXXXX XXXXXX XX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XX X
    XXXXXXXXXXXXXXXXXX X XXXXXXX
    XXXXXXXXXXXXXXXXXX X XXX
    XXXXXXXXXXXX X XXXXX

    XX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXXXXXX XX XXXXX
    XXXXX XXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      XX
      XXXXXXXXX XXXXXXXXXXXXXX
    XXX

    XX XXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX X XXXXXX
      XXXXXXX
    X

    XXXXX XX X XXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXX XXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXX XXXXXXXX XXXXXXX X XX XXXX XXX
    XXXXX XXXXXX X XXXXXXXXXX XX XXXXXXXXXX

    XXXXXXXXXXXXXXXXXX X XXXXXXXX

    XX XXXXXXX XXX XXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X
        X gettext(u'Оплата авторизована (HOLD). Ожидает подтверждения админом.') XX
      XX XXXXX XXXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX
      XXXXXXX
    X

    XX XXXXXXX XXX XXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X X gettext(u'Оплата завершена (succeeded).') XX
      XXXXXXX
    X

    XX XXXXXXX XXX XXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X
        X gettext(u'Платіж в обробці (processing). Статус оновиться після webhook.') XX
      XXXXXXX
    X

    XX XXXXXXX XXX XXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X
        X gettext(u'Потрібна додаткова дія (3DS). Дотримуйтесь інструкцій Stripe.') XX
      XXXXXXXXXXXX X XXXXXX
      XXXXXXX
    X

    XX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXX X XXXXXXX
      XXXXXXXXXXXXXXXXXX X
        X gettext(u'Платіж не підтверджено: потрібен інший спосіб оплати.') XX
      XXXXXXXXXXXX X XXXXXX
      XXXXXXX
    X

    XX XXXXXXXX
    XXXXXXXXXXXXXXXXXX X X gettext(u'Платіж створено. Stripe status:')  XXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB