BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX
XXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XX

XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XX XXXXX XXXXXXX XXXX XXXXXXXXX XXXX XXXXXXXXX

  XXXX XXXXX XXXXXXXXX XXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX X XXXXXXX XX XXXXXXXXX XXXX XX XXXXX XXXXXX XX XXXXX X XXXXXXXX XXXXXXXXX X XXXXXXXX XXXXXX XXXXXX X XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXXX XXXXXXXXXXX
          XXXXXXXXXX XXXX X XXXXXXXXXXXX
          XXXXXXXXXXXXXX XXXXXX X XXXXXXXXXXXX
          XXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXX
        XXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXBBBBBXX
          BB BBBBBBBBBBBBBBBB BB BXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXBBBBXXXXXBBBBB XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXX  XXXXX
          XXXXXXXXXXXXXXXX
        XXXXXX
      BBBBBB
    XXXXXX
  XXXXXX

  XXXX XXXXX XXXXXXXXX XXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XXXX XX XXX XXXXXX XXXXX XXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XX XXXXXXX XXXXX XXXXX X XXXXXXX XXXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXX XX XXXXXXXXXX
          XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXX
        XXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      BBB BBBBBB BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXBBBBBXX
          BB BBBBBBBBBBBBBBBB BB BXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXXX
            XXXXXXXXXXXXX
            XXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BXXXXXXXBBBBXXXXXBBBBB XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXX  XXXXX
          XXXXXXXXXXXXXXXX
        XXXXXX
      BBBBBB
    XXXXXX
  XXXXXX

  XXXX XXXXX XXXXXXXXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXX XXXXX XX XXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXX

XXXXXX

XXXX XXXXX XXXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXXXX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Закрити') XX
      XXXXXXX
    XXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Заявка на рекламу') XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Заповніть форму нижче — після цього наш адміністратор зв\\') 
    XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXX XXX
      XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Фото реклами') XXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX gettext(u'Текст оголошення') X
          XXXXXXXXXXXXXXXXXXX gettext(u'Alt текст банера (не відображається на зображенні)') X
        X gettext(u'Текст оголошення') XXXXXXXX
        XXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Наприклад: iPhone 13 Pro, ідеальний стан, повний комплект, торг доречний') X
          XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Наприклад: Знижки до -30%% на всі товари цього тижня') X
          XXXXXXXXXXXXX gettext(u'Наприклад: iPhone 13 Pro, ідеальний стан, повний комплект, торг доречний') X
          XXXXXXXX
        XXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Цей текст не показується на самому банері — він потрібен як alt-текст зображення (для доступності та SEO). Сам текст акції додайте прямо на зображення банера.') 
        XXXX

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Посилання (необов\\') XXXXXXXX
        XXXXXX
          XXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Наприклад: посилання на ваш магазин чи товар') X
          XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Наприклад: посилання на сторінку акції') X
          XXXXXXXXXXXXX gettext(u'Наприклад: посилання на ваш магазин чи товар') X
        X

        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Контакт (email, Telegram @нік або телефон)') XXXXXXXX
        XXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXX gettext(u'Наприклад: user@mail.com або @username') X
          XXXXXXXX
        X

        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Надіслати заявку') 
        XXXXXXXXX
      XXXXXXX

      XXXX XXXX XXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Так виглядатиме на сайті') XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'TOP') XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'фото ще не завантажено') 
          XXXXXX
          XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX gettext(u'текст оголошення зʼявиться тут') X
            XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'alt-текст зʼявиться тут') X
          XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX gettext(u"Дякуємо! Заявку прийнято. Очікуйте, адміністратор незабаром зв'яжеться з вами щодо оплати.") XXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB