BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBB
XXXXXXX gettext(u'SELECT payment') XXXXXXXX

XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXX gettext(u'Рекламный банер') XXXXXXXXX
XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXX gettext(u'Рекламный пост') XXXXXXXXX

BBBBBBBB