# Generated by Django 5.2.9 on 2026-01-29 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('process', 'В процессе'), ('agree', 'Решена'), ('denied', 'Откланена')], default='process', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('other', 'другое'), ('spam', 'спам'), ('scam', 'обман'), ('forbidden', 'запрещёнка 18+'), ('fake', 'Фейк'), ('toxic', 'Грубость оскорбление'), ('catfish', 'Выдает себя за другого человека')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('process', 'В процессе'), ('agree', 'Решена'), ('denied', 'Откланена')], default='process', max_length=50)),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос жалобы',
                'verbose_name_plural': 'Запросы жалоб',
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_claim_per_user')],
            },
        ),
    ]
