# Generated by Django 5.2.9 on 2026-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
    ]
