# Generated by Django 5.2.9 on 2026-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_supportticket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'verbose_name': 'запит скарги', 'verbose_name_plural': 'запит скарги'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'тикет підтримки', 'verbose_name_plural': 'тикетм підтримки'},
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.CharField(choices=[('other', 'інше'), ('spam', 'спам'), ('scam', 'обман'), ('forbidden', 'заборонена 18+'), ('fake', 'фейк'), ('toxic', 'грубість образа'), ('catfish', 'видає себе за іншу людину')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('process', 'в процесі'), ('agree', 'вирішена'), ('denied', 'відкланено')], default='process', max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('process', 'в процесі'), ('agree', 'вирішена'), ('denied', 'відкланено')], default='process', max_length=50),
        ),
    ]
