# Generated by Django 5.2.9 on 2026-04-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_claimrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
