# Generated by Django 5.2.9 on 2026-04-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('support', '0005_trackedlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'verbose_name': 'Claim request', 'verbose_name_plural': 'Claim requests'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'verbose_name': 'Support ticket', 'verbose_name_plural': 'Support tickets'},
        ),
        migrations.AlterModelOptions(
            name='trackedlink',
            options={'verbose_name': 'Tracked link', 'verbose_name_plural': 'Tracked links'},
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.CharField(choices=[('other', 'Other'), ('spam', 'Spam'), ('scam', 'Scam'), ('forbidden', 'Forbidden 18+'), ('fake', 'Fake'), ('toxic', 'Rudeness or insult'), ('catfish', 'Impersonation')], default='other', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('process', 'In progress'), ('agree', 'Resolved'), ('denied', 'Denied')], default='process', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('process', 'In progress'), ('agree', 'Resolved'), ('denied', 'Denied')], default='process', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='trackedlink',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='trackedlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='trackedlink',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='trackedlink',
            name='original_url',
            field=models.URLField(verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='trackedlink',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
