# Generated by Django 5.2.9 on 2026-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_claimrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='reason',
            field=models.CharField(choices=[('other', 'Other'), ('spam', 'Spam'), ('scam', 'Scam'), ('forbidden', 'Forbidden (18+)'), ('fake', 'Fake'), ('toxic', 'Rude or offensive'), ('catfish', 'Impersonation')], default='other', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
