# Generated by Django 5.2.9 on 2026-08-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_claimrequest_reason_alter_claimrequest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
