# Generated by Django 5.2.9 on 2026-01-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_toppromotion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppromotion',
            name='status',
        ),
    ]
