# Generated by Django 5.2.9 on 2026-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_toppromotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advpromotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
