# Generated by Django 5.2.9 on 2026-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_advpromotion_ends_at_advpromotion_starts_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('amount_capturable', models.BigIntegerField(blank=True, null=True)),
                ('livemode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
