# Generated by Django 5.2.9 on 2026-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='advpromotion',
            name='last_intent_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='advpromotion',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advpromotion',
            name='last_webhook_event',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='last_intent_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='last_webhook_event',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
