# Generated by Django 5.2.9 on 2026-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_advpromotion_last_intent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
