# Generated by Django 5.2.9 on 2026-02-01 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_fill_checkout_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='checkout_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
