# Generated by Django 5.2.9 on 2026-02-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_pendingadvpromotion_checkout_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advpromotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pendingadvpromotion',
            name='description',
        ),
    ]
