# Generated by Django 5.2.9 on 2026-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_advpromotion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingadvpromotion',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
