# Generated by Django 5.2.9 on 2026-04-30 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0012_pendingadvpromotion_is_refunded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advpromotion',
            options={'verbose_name': 'Advertisement promotion', 'verbose_name_plural': 'Advertisement promotions'},
        ),
        migrations.AlterModelOptions(
            name='pendingadvpromotion',
            options={'verbose_name': 'Pending promotion', 'verbose_name_plural': 'Pending promotions'},
        ),
        migrations.AlterModelOptions(
            name='toppromotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Top promotion', 'verbose_name_plural': 'Top promotions'},
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='ad_type',
            field=models.CharField(max_length=50, verbose_name='Ad type'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ends at'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is frozen'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='last_intent_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Last intent status'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last webhook at'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='last_webhook_event',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last webhook event'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='payment_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='advpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='ad_type',
            field=models.CharField(max_length=50, verbose_name='Ad type'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='checkout_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Checkout key'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='duration_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Is refunded'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='last_intent_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Last intent status'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last webhook at'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='last_webhook_event',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last webhook event'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='payment_intent_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Payment intent ID'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Refund ID'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pendingadvpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='amount_capturable',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Capturable amount'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='event_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Event ID'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='event_type',
            field=models.CharField(max_length=120, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='livemode',
            field=models.BooleanField(default=False, verbose_name='Live mode'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment intent ID'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='pending_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Pending ID'),
        ),
        migrations.AlterField(
            model_name='stripewebhookevent',
            name='status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'ads'), ('model__in', ['jobpost', 'thingspost', 'neighborpost'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ends at'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='toppromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_promotions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
