# Generated by Django 5.2.9 on 2026-07-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_advpromotion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unique_amount', models.DecimalField(decimal_places=6, max_digits=12, unique=True)),
                ('currency', models.CharField(default='USDT', max_length=10)),
                ('chain', models.CharField(default='TRX', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('expired', 'Истёк')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tx_id', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='advpromotion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pendingadvpromotion',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripeWebhookEvent',
        ),
        migrations.RemoveField(
            model_name='toppromotion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='toppromotion',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdvPromotion',
        ),
        migrations.DeleteModel(
            name='PendingAdvPromotion',
        ),
        migrations.DeleteModel(
            name='TopPromotion',
        ),
    ]
