# Generated by Django 5.2.9 on 2026-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_order_duration_days_order_post_id_order_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('crypto', 'Крипта (USDT)'), ('revolut', 'Revolut'), ('card_ua', 'Українська картка')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='unique_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, unique=True),
        ),
    ]
