# Generated by Django 5.2.9 on 2026-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('up', 'покращити оголошення'), ('post', 'рекламний пост'), ('banner', 'рекламний банер')], default=None, max_length=100),
        ),
    ]
