# Generated by Django 5.2.9 on 2026-07-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_order_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('up', 'покращити оголошення'), ('post', 'рекламний пост'), ('banner', 'рекламний банер')], default='up', max_length=100),
        ),
    ]
