# Generated by Django 5.2.9 on 2026-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_order_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_submissions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='ad_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ad_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
